### ISSUE TITLE
include helm package in releases

### ISSUE THREAD

**Issue by davidsiefert** [spotahome/redis-operator#104]
### Expected behaviour

Want to be able to `helm install https://github.com/path/to/redis-operator-chart/release.tar.gz` to quickly and easily install redis-operator.

### Actual behaviour

First I need to either install git and checkout the repo at tag, then install from local filesystem *or* download the complete src archive, extract it, and helm install from local filesystem.  Makes automation more of an effort.

**Comment by mcanevet** [comment]
We also want to install this using `helmfile` and AFAIK it requires the chart to be available in a charts repository.

**Comment by ese** [comment]
closed by #292
