### ISSUE TITLE
Possible to use multiple sentinels/slaves for reads?

### ISSUE THREAD

**Issue by roynasser** [spotahome/redis-operator#106]
### Expected behaviour

In order to scale reads/connections, we would like reads to be split over several replicas/slaves of a main Redis master.  Is this something supported with the operator? 

### Actual behaviour

Unknown yet...

**Comment by jchanam** [comment]
Hi @RVN-BR,

The operator is in charge of manage the redis setup and livecycle, not about the Redis usage by clients. It ensures (thanks to Sentinel too) that there is one master and N-1 slaves (being N the number of redis set on the RedisFailover Spec).

It's totally possible to read (also) from redis nodes working as slaves. You need to use a client that is able to do so.

I hope I helped you.

**Comment by RVN-BR** [comment]
Hi @jchanam That sounds good... simpler than I expected, which is good...

I'm going to get my hands dirty pretty soon on this, before I do, however, is there any selector/label I can use to identify replicas, for example, and setup a service for Read Replicas, as opposed to doing it in the app layer or with an external haproxy?
