### ISSUE TITLE
Redis Operator did not update deployment after k8s worker crashed

### ISSUE THREAD

**Issue by normander** [spotahome/redis-operator#107]
How should behave redis-cluster after crashed k8s worker node where is one of pods of deployment?
After crashed node, Redis-Operator did not create new pod for deployment.

**Comment by jchanam** [comment]
Hi,

The operator trusts in Kubernetes to manage the lifecycle of the pods. That's why it uses a deployment for the sentinel pods and a statefulset for redis pods.

I don't know if you're facing an error from the operator or from your Kubernetes cluster. Could you please provide more information so I can help you better?

**Comment by normander** [comment]
Dis you used statefulset because of static identifier? We need to create some solution for remove pod from unreachable node from etcd to recreate to another one.

**Comment by jchanam** [comment]
Hi, yes. We use it because each pod of a redis statefulset is different from the other, also, they can have persistent storage.

**Comment by normander** [comment]
I've checked a lot of from your solution. We have a big cluster and things like a crashed dynamic worker node of kubernetes is a normal situation for us. Solution for me is additional container in redis-operator pod which connected to k8s stream and checking if some pod is in unknow state then it killed them - specially for statefulset.

**Comment by jchanam** [comment]
Thanks for sharing your way to fix it!

I use also dynamic nodes on K8S, but I'm not facing that issue of unknown state.

Is there any way I can help you with this?

**Comment by normander** [comment]
No, I agree with this. What do you use for dynamic nodes? Private\public cloud? That is the last question in this topic :)

**Comment by jchanam** [comment]
I use AWS, with spot instances. They can be deleted in any moment.

Also, for managing the number of nodes, I use the [cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler).

I hope this helps you.

**Comment by tkrop** [comment]
@jchanam can you share some information on how to setup the auto-scaling correctly?

I'm currently trying this out, but had to override the redisfailover CRD to make it possible and still thinks are not as they should be. I have the feeling I'm not doing it the right way. May be you can give me some hints.

**Comment by tkrop** [comment]
@jchanam seems to have been an issue with our Kubernetes setup. It now works fine.

**Comment by ese** [comment]
Thanks @tkrop
