### ISSUE TITLE
Any way to connect the redis cluster from outside 

### ISSUE THREAD

**Issue by pmquang** [spotahome/redis-operator#109]
Hi, 

The redis cluster will be connected through sentinel service.  So it's quite hard to connect the cluster from the outside of K8S because sentinel returns the private ip of k8s system.

Any suggestion ?

**Comment by paol** [comment]
Hi,

We need this feature and will probably implement it ourselves. Would you accept a pull request that adds "hostNetwork" and "dnsPolicy" to types RedisSettings and SentinelSettings? These would basically just be forwarded unchanged to the PodSpec.

**Comment by chusAlvarez** [comment]
Solved indeed in the PR #212 . Thanks, @paol !

**Comment by databasedav** [comment]
This enables connecting to the sentinel from the host machine, correct? Can how to do this be added to the documentation. I'm new to k8s and would really appreciate it. Thanks!

**Comment by laukaichung** [comment]
Would anyone please explain how to connect redis from the outside? I've set `hostNetwork: true` to both `sentinel` and `redis` spec but it doesn't work.
