### ISSUE TITLE
get-master-addr-by-name is 127.0.0.1

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [spotahome/redis-operator#120]
$ kubectl exec -it rfs-redisfailover-78b58d7db7-5z7mb -- redis-cli -p 26379 SENTINEL get-master-addr-by-name mymaster
1) "127.0.0.1"
2) "6379"

the resulting IP address is 127.0.0.1
So continue with the following command
$ kubectl exec -it rfs-redisfailover-78b58d7db7-5z7mb -- redis-cli -h 127.0.0.1 -p 6379 SET hello world!
Could not connect to Redis at 127.0.0.1:6379: Connection refused
command terminated with exit code 1

Excuse me, what seems to be the problem?

**Comment by wanghe-fit2cloud** [comment]
### basic.yaml:
apiVersion: storage.spotahome.com/v1alpha2
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    customConfig:
      - "down-after-milliseconds 2000"
      - "failover-timeout 3000"
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 1000Mi
  redis:
    replicas: 3
    customConfig:
      - "maxclients 100"
      - "hz 50"
      - "timeout 60"
      - "requirepass 123456"
    image: 10.1.240.55:1180/redis/redis
    version: 3.2-alpine
    storage:
      keepAfterDeletion: true
      persistentVolumeClaim:
        metadata:
          name: redisfailover-persistent-keep-data
        spec:
          storageClassName: managed-nfs-storage
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 1000Mi

**Comment by wanghe-fit2cloud** [comment]
changed the local image and added the requirepass on the basis of the original file

**Comment by wanghe-fit2cloud** [comment]
### $ kubectl logs -f rfr-redisfailover-1
1:S 25 Feb 10:47:19.075 * Retrying with SYNC...
1:S 25 Feb 10:47:19.076 # MASTER aborted replication with an error: ERR Can't SYNC while not connected with my master
1:S 25 Feb 10:47:20.077 * Connecting to MASTER 127.0.0.1:6379
1:S 25 Feb 10:47:20.077 * MASTER <-> SLAVE sync started
1:S 25 Feb 10:47:20.077 * Non blocking connect for SYNC fired the event.
1:S 25 Feb 10:47:20.077 * Master replied to PING, replication can continue...
1:S 25 Feb 10:47:20.078 * Partial resynchronization not possible (no cached master)
1:S 25 Feb 10:47:20.078 * Master does not support PSYNC or is in error state (reply: -ERR Can't SYNC while not connected with my master)
...
### $ kubectl logs -f rfs-redisfailover-78b58d7db7-dgmcm 
1:X 21 Feb 09:49:34.372 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:X 21 Feb 09:49:34.373 # Sentinel ID is 6366466b8749514241bd025f72c6901ed0d2c28f
1:X 21 Feb 09:49:34.373 # +monitor master mymaster 127.0.0.1 6379 quorum 2
1:X 21 Feb 09:49:35.411 # +sdown master mymaster 127.0.0.1 6379
### $ kubectl logs -f redisoperator-645f454c9d-86ftm
time="2019-02-25T10:49:39Z" level=error msg="Error processing redis-operator/redisfailover: NOAUTH Authentication required." controller=redisfailover operator=redisfailover src="generic.go:223"
time="2019-02-25T10:50:03Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:04Z" level=info msg="configMap updated" configMap=rfr-s-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:04Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:04Z" level=info msg="podDisruptionBudget updated" namespace=redis-operator podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-02-25T10:50:04Z" level=info msg="statefulSet updated" namespace=redis-operator service=k8s.statefulSet src="statefulset.go:96" statefulSet=rfr-redisfailover
time="2019-02-25T10:50:04Z" level=info msg="podDisruptionBudget updated" namespace=redis-operator podDisruptionBudget=rfs-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-02-25T10:50:04Z" level=info msg="deployment updated" deployment=rfs-redisfailover namespace=redis-operator service=k8s.deployment src="deployment.go:96"
time="2019-02-25T10:50:04Z" level=warning msg="error processing redis-operator/redisfailover job (requeued): NOAUTH Authentication required." controller=redisfailover operator=redisfailover src="generic.go:223"
time="2019-02-25T10:50:04Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:04Z" level=info msg="configMap updated" configMap=rfr-s-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:05Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:05Z" level=info msg="podDisruptionBudget updated" namespace=redis-operator podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-02-25T10:50:05Z" level=info msg="statefulSet updated" namespace=redis-operator service=k8s.statefulSet src="statefulset.go:96" statefulSet=rfr-redisfailover
time="2019-02-25T10:50:05Z" level=info msg="podDisruptionBudget updated" namespace=redis-operator podDisruptionBudget=rfs-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-02-25T10:50:05Z" level=info msg="deployment updated" deployment=rfs-redisfailover namespace=redis-operator service=k8s.deployment src="deployment.go:96"
time="2019-02-25T10:50:05Z" level=warning msg="error processing redis-operator/redisfailover job (requeued): NOAUTH Authentication required." controller=redisfailover operator=redisfailover src="generic.go:223"
time="2019-02-25T10:50:06Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:06Z" level=info msg="configMap updated" configMap=rfr-s-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:07Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:07Z" level=info msg="podDisruptionBudget updated" namespace=redis-operator podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-02-25T10:50:07Z" level=info msg="statefulSet updated" namespace=redis-operator service=k8s.statefulSet src="statefulset.go:96" statefulSet=rfr-redisfailover
time="2019-02-25T10:50:07Z" level=info msg="podDisruptionBudget updated" namespace=redis-operator podDisruptionBudget=rfs-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-02-25T10:50:07Z" level=info msg="deployment updated" deployment=rfs-redisfailover namespace=redis-operator service=k8s.deployment src="deployment.go:96"
time="2019-02-25T10:50:07Z" level=warning msg="error processing redis-operator/redisfailover job (requeued): NOAUTH Authentication required." controller=redisfailover operator=redisfailover src="generic.go:223"
time="2019-02-25T10:50:08Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:08Z" level=info msg="configMap updated" configMap=rfr-s-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:08Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=redis-operator service=k8s.configMap src="configmap.go:76"
time="2019-02-25T10:50:08Z" level=info msg="podDisruptionBudget updated" namespace=redis-operator podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-02-25T10:50:08Z" level=info msg="statefulSet updated" namespace=redis-operator service=k8s.statefulSet src="statefulset.go:96" statefulSet=rfr-redisfailover
time="2019-02-25T10:50:09Z" level=info msg="podDisruptionBudget updated" namespace=redis-operator podDisruptionBudget=rfs-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-02-25T10:50:09Z" level=info msg="deployment updated" deployment=rfs-redisfailover namespace=redis-operator service=k8s.deployment src="deployment.go:96"
time="2019-02-25T10:50:09Z" level=error msg="Error processing redis-operator/redisfailover: NOAUTH Authentication required." controller=redisfailover operator=redisfailover src="generic.go:223"

**Comment by jchanam** [comment]
Hi @wanghe-fit2cloud,

As I've seen in your config, you're trying to use a password for securing redis. This is not currently supported, but a discussion is progress to have this possibility in #66.

You're getting `127.0.0.1` as master IP because when a sentinel pod is created, it's configured to monitor itself (so it's running and the operator can manage it afterwards). Because of the auth in redis, the sentinel is not able to connect to it, so it'll never monitor the master.

It's said in the logs:
```
time="2019-02-25T10:50:04Z" level=warning msg="error processing redis-operator/redisfailover job (requeued): NOAUTH Authentication required." controller=redisfailover operator=redisfailover src="generic.go:223"
```

PS: Please, [quote the contents](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) of files/logs in the comments so it's easy to read.

**Comment by wanghe-fit2cloud** [comment]
The reason for the failure was that I set up requirepass. 
Thank you very much！

### But I have another question which is how can I access the redis service externally?
For example, if my springboot service is not deployed to the k8s cluster, the access service will report an exception: Could not get a resource from the pool

**Comment by jchanam** [comment]
There's no official way to access from the outside, because of the specifics of how to connect via sentinel to the redises. A question about this was already made: https://github.com/spotahome/redis-operator/issues/109
