### ISSUE TITLE
Redis custom config not working

### ISSUE THREAD

**Issue by marcemq** [spotahome/redis-operator#124]
### Expected behaviour

Verify that redis custom config is properly applied.

### Actual behaviour

After the proper installing operator from `master` branch and deploy `example/redisfailover/custom-config.yaml` the provided `customConfig` is not updated in the `redis.conf` file, it shows only the default configuration set [here](https://github.com/spotahome/redis-operator/blob/master/operator/redisfailover/service/generator.go#L109).
**NOTE**: the `customConfig` for the sentinel instances gets updated at the `sentinel.conf` file, see the logs below.

### Steps to reproduce the behaviour

* Install operator from `master` branch.
* Deployment of `example/redisfailover/custom-config.yaml` (with `failover-timeout 2000` to validate updates at sentinel section)
* Get configuration files used for redis instances and to verify that the `customConfig` is not shown (see detailed steps at Logs)

### Environment

How are the pieces configured?
* Redis Operator from 'master' branch.
* Kubernetes version: v1.13.0
* Kubernetes configuration used: RBAC active

### Logs
```
$ kubectl get po
NAME                                           READY   STATUS    RESTARTS   AGE
pmem-csi-controller-0                          4/4     Running   0          47m
pmem-csi-khnh4                                 2/2     Running   1          47m
redisfailover-redisoperator-68c8fdb97c-sfqxr   1/1     Running   0          37m
rfr-redisfailover-0                            1/1     Running   0          5m3s
rfr-redisfailover-1                            1/1     Running   0          4m27s
rfr-redisfailover-2                            1/1     Running   0          3m49s
rfs-redisfailover-6757fff98b-4dfjt             1/1     Running   0          5m3s
rfs-redisfailover-6757fff98b-gk6mn             1/1     Running   0          5m3s
rfs-redisfailover-6757fff98b-rg9zn             1/1     Running   0          5m3s

## match the name of one redis and sentinel to a docker container ID, for this example: 
## redis => 4a3667588f3e
## sentinel =>  e471ecf6d20e

## print redis config files
# docker exec -it 4a3667588f3e sh
/data # cat /redis/redis.conf
slaveof 127.0.0.1 6379
tcp-keepalive 60
save 900 1
save 300 10

## print redis config files
# docker exec -it e471ecf6d20e sh
/data # cat /redis/sentinel.conf
sentinel myid 7965695f8ff64749003f1057c2d909912f499598
sentinel monitor mymaster 10.244.1.24 6379 2

# Generated by CONFIG REWRITE
port 26379
dir "/data"

sentinel down-after-milliseconds mymaster 2000
sentinel failover-timeout mymaster 2000
sentinel config-epoch mymaster 0
sentinel leader-epoch mymaster 0
sentinel known-slave mymaster 10.244.1.29 6379

sentinel known-slave mymaster 10.244.1.28 6379
sentinel known-sentinel mymaster 10.244.1.25 26379 89069f776ff31b837c0381a0e592e1abe4fd835b
sentinel known-sentinel mymaster 10.244.1.27 26379 24d9624ef304228739c008d9a860fc1649e8ef21
sentinel current-epoch 0
```

**Comment by jchanam** [comment]
Hi @marcemq,

You're right, the configuration set on `customConfig` does not appear on the configMap. We decided to work this way due to the possible changes on configuration made by the users.

If we write the configuration on the ConfigMap, that would need the redises/sentinels to restart. Instead of doing that, the operator sends `CONFIG SET` commands so the configuration of the `customConfig` is used and there's no need for redises to restart.

In the case of Sentinel, it's used the same way, but because of Sentinel work logic, it rewrites the configuration on it's file with a `CONFIG REWRITE`.

Would it make sense to send a `CONFIG REWRITE` to the redises just to see it on the configuration file?

If you want to check the actual configuration for redis, you can [ask them directly](https://redis.io/commands/config-get):

```
kubectl exec -ti rfr-<name>-<N> -- redis-cli CONFIG GET <parameter>
```
(You can also get all config calling with `*`)

Here you have information about this on the [README.md](https://github.com/spotahome/redis-operator#custom-configurations). If it's not clear enough, I'll be happy to improve it with your input.

**Comment by marcemq** [comment]
Hi @jchanam,

> Would it make sense to send a `CONFIG REWRITE` to the redises just to see it on the configuration file?
Ans: Well, for a consistent behaviur for the configuration files in place I would say yes.

But at the end we have two option: 
1. Add the `CONFIG REWRITE` to the redises asnd I think the change is relatively small, right? (see [draft PR125](https://github.com/spotahome/redis-operator/pull/125))
2. Improve the documentation as you already pointed out.

Both options are equally good to me. Are you more lean towards any option?

**Comment by jchanam** [comment]
As I commented on the PR, I think adding the `config rewrite` adds complexity and does not improve the usage of redis-failovers.

I'd add, if necessary, more information on the documentation.

**Comment by marcemq** [comment]
Agree.

**Comment by Kyrremann** [comment]
I want to follow up here, as I'm trying to turn off RDB, and I'm having problem seeing that the custom changes have been made.

My `redisfailovers.yml`
```
---
apiVersion: storage.spotahome.com/v1alpha2
kind: RedisFailover
metadata:
  name: kyrre-redisfailover
  labels:
    app: kyrre-test
    team: aura
spec:
  sentinel:
    replicas: 3
  redis:
    replicas: 3
    customConfig:
      - "appendonly no"
      - "save \"\""
```

They all starts okay, and the configmap is showing the default config as stated in this thread, but when I try to use `redis-cli`, it still show me the default settings.

```
$ kubectl exec -ti rfr-kyrre-redisfailover-2 redis-cli config get save
1) "save"
2) "900 1 300 10"
```

Any tips on what I'm doing wrong, or what I can further debug?

**Comment by jchanam** [comment]
Hi @Kyrremann,

I've checked and I think it's an issue with the go-redis library. I'll try to go deeper with it to get to a solution.

**Comment by Kyrremann** [comment]
@jchanam Found out something more here? Or do you have any tips for other ways I can solve my problem?

**Comment by jchanam** [comment]
@Kyrremann I've been trying, but unfortunately it get to the conclusion that is not possible at this moment.

How critical is for you disabling the save on disk?

**Comment by Kyrremann** [comment]
Okay, thanks. It's semi critical, cause we don't have storage, so some of our Redis-instances crashes when they try to create a backup.

I'll try to look into fixing it a different way. Probably overwriting the default configmap or something like that.

**Comment by VassyutovichIlya** [comment]
@Kyrremann Hi! I've found a "workaround" of sort for disabling rdb-saving and providing empty-string values for configuration options in general:

```yaml
# ...
  customConfig:
    - "save "
    - "notify-keyspace-events "
# ...
```
