### ISSUE TITLE
Any way to use a dynamic service to communicate with the master?

### ISSUE THREAD

**Issue by sneko** [spotahome/redis-operator#138]
Hi,

I'm stuck for a few months because I'm using Istio and when trying to talk directly with the Redis master IP, it fails due to Istio/Envoy modification on the connection/message.

You can find my issue here: https://github.com/istio/istio/issues/8836

The only solution I've heard about is to exclude all my cluster pods IP range to be sure that Istio will not modify the request when communicating with Redis master... but that's not a fine-grained solution 😢 (moreover the Pods IP range changes over Kubernetes updates on my side).

So I thought about a solution: create a service to target the right Redis node. I would deploy a little exec to loop every 5s to ask Sentinel nodes "who is the master", and if I detect a changement I would use Kubectl client to update my service and make it targetting the appropriate Redis master pod.

But before doing this, I would like your thoughts because maybe I missed something to get things done in an easier way 👍 

Thank you,

**Comment by schlitzered** [comment]
i am currently evaluating the use of this operator, and to solve to issue of clients being not aware of redis sentinel, it strumbled across this project: 

https://github.com/anubhavmishra/redis-sentinel-proxy

looks like this could solve the issue perfectly if used a a side car container in the application pod using redis.

but i did not jet had the chance to try this.

**Comment by yylt** [comment]
@sneko 
hi, i had submit PR https://github.com/spotahome/redis-operator/pull/132 , but as @jchanam said , the operator can only guarantee the connection through Sentinel. 

so you  can create redis service  by label redisfailover={name} and use haproxy to find master 
haproxy config can be below:

~~~
    listen redis-status
      bind 0.0.0.0:6379
      mode tcp
      option tcplog
      option tcp-check
      tcp-check send PING\r\n
      tcp-check expect string +PONG
      tcp-check send info\ replication\r\n
      tcp-check expect string role:master
      tcp-check send QUIT\r\n
      tcp-check expect string +OK
      server redis0 redis-failover-0:6379 check inter 3s
      server redis1 redis-failover-1:6379 check inter 3s
      server redis2 redis-failover-2:6379 check inter 3s
~~~

**Comment by nrvnrvn** [comment]
Hey folks! 
Shameless plug. You could try this redis operator https://github.com/amaizfinance/redis-operator

It can be considered a kubernetes native Sentinel replacement and if I understood correctly does exactly what you want - maintains a service pointing to actual master node.

**Comment by sneko** [comment]
Hi @nrvnrvn!

Great news, thank you for your work. I hope yours will become famous and also supported by the community 😄 

I just installed the cluster, and tried with a test pod with Istio injected, and it works well! Congrats!

By the way, some improvements I think about:
- In the operator logs, display a human readable datetime
- For massive adoption, embed `deploy` directory in a Helm chart

Tomorrow I will try to integrate this into all my microservices, replacing all the mechanic of dealing with Sentinel ^^...

**Comment by nrvnrvn** [comment]
Hi @sneko,

thanks a lot for the positive feedback!

Logs' time format is annoying I agree. Unfortunately this format is imposed by either controller-runtime or operator-sdk. I will raise this issue with them because rfc3339 formatted timestamps would be a much better option.

Helm charts is something I've personally tried to avoid 😊 but it looks like I will change my opinion in the nearest future.
