### ISSUE TITLE
Can you introduce the implementation logic of the redis sentinel mode in this operator?

### ISSUE THREAD

**Issue by AllenZMC** [spotahome/redis-operator#151]
Can you introduce the implementation logic of the redis sentinel mode in this operator?  Thanks! 

Why is this setting? Can the sentinel monitor redis with 127.0.0.1 ?
```
sentinel monitor mymaster 127.0.0.1 6379 2

slaveof 127.0.0.1 6379
```

**Comment by AllenZMC** [comment]
hi, I get it.
"After the startup of the pieces, the operator will reconfigure them to monitor the real master."  Where is this operation implemented in the code, can you refer to it?

**Comment by jchanam** [comment]
You're completely right. I think this was caused when we changed the logic to control the loops from the checker. I'll fix it.

**Comment by AllenZMC** [comment]
Look at the following code.  This function gets the sentry's slave or the redis slave？
```
func (c *client) GetNumberSentinelSlavesInMemory(ip string)
```
In my opinion, the information obtained by the `redis-cli info sentinel` is the number of redis slaves rather than the number of sentinel slaves.
```
slaveNumberREString     = "slaves=([0-9]+)"
```

**Comment by jchanam** [comment]
That function checks that the info the sentinel is managing is correct. In not, a request to refresh the data will be sent.

You're right about the information `info sentinel` gives, and that's exactly the goal of the check.

**Comment by AllenZMC** [comment]
`nSlaves != rf.Spec.Sentinel.Replicas-1` What does this logic mean?
```
for _, sip := range sips {
		nSlaves, err := r.redisClient.GetNumberSentinelSlavesInMemory(sip)
		if err != nil {
			return err
		} else if nSlaves != rf.Spec.Sentinel.Replicas-1 {
			return errors.New("sentinels in memory mismatch")
		}
	}
```

**Comment by jchanam** [comment]
Yep, that was a bug, it's being fixed in the new v1. As soon as I create the PR I'll reference the issue

**Comment by AllenZMC** [comment]
Where is crd yaml?

**Comment by jchanam** [comment]
There's no a generated yaml with the CRD information.

The operator, thanks to [kooper](https://github.com/spotahome/kooper), registers the CRD directly to k8s.
