### ISSUE TITLE
custom config set before redis running

### ISSUE THREAD

**Issue by halimess** [spotahome/redis-operator#172]
### Expected behaviour

Set some config, before redis running.
In Redis config, logfile is needed to be set, before running.
it can't be set after.

### Actual behaviour

customConfig is set only after redis running.

### Steps to reproduce the behaviour

<pre>
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
    name: rediscluster
spec:
    sentinel:
        replicas: 3
    redis:
        replicas: 3
        customConfig:
            - "logfile /var/log/redis-server.log"
</pre>

create init container which copy conf file to emptydir, just like sentinel do.
And take that customConfig to redis.conf file

### Environment

N/A

### Logs
<pre>
127.0.0.1:6379> config get logfile
1) "logfile"
2) "/var/log/redis-server.log"
127.0.0.1:6379> config set logfile /var/log/server.log
(error) ERR Unsupported CONFIG parameter: logfile
127.0.0.1:6379>
</pre>

**Comment by halimess** [comment]
And I add a new scenario.

If cluster environment has NAT, then user maybe need to set announce with pod's ip
<a>https://redis.io/topics/replication#configuring-replication-in-docker-and-nat</a>

This config can be set after running, but it makes user do it manually.
Because, when creating pod, we can't know where pod is in, and what ip is.

**Comment by marcemq** [comment]
Hello there 😊 

I've opened an [issue related to this](https://github.com/spotahome/redis-operator/issues/124  ) and @jchanam's answer on it might help to clarify the `customConfig` behavior.

**Comment by ese** [comment]
I'm closing this issue for stale state. Feel free to reopen if the problem persists.

**Comment by rdxmb** [comment]
/reopen please

What about the question of [@YuseongJay ](https://github.com/spotahome/redis-operator/issues/172#issuecomment-506665842 ) , is there a solution to create an instance through the operator with `announce_ip`s ? We need this to connect the redis-cluster from outside kubernetes.
