### ISSUE TITLE
Question: Starting RedisFailover to replicate from existing redis instance

### ISSUE THREAD

**Issue by alecjacobs5401** [spotahome/redis-operator#198]
Hey all,

Quick question: I'm wondering if there is a known workaround/hack to put in place that will allow me to spinup a new `RedisFailover` instance that replicates from a pre-existing Redis instance?

I'm hoping to launch a `RedisFailover` instance soon and it would very convenient to not lose any existing data we have. Right now the operator is thwarting any of my attempts to manually set a master.

Just curious if this use case has been thought up / a known workaround is possible!

Thanks!

P.S - setting `slaveof` in the redis config seems to be directly unsupported (this is what I hoped would work out of the gate)
```
time="2019-11-04T20:02:59Z" level=warning msg="error processing aj-redis/redisfailover job (requeued): ERR Unsupported CONFIG parameter: slaveof" controller=redisfailover operator=redis-operator src="generic.go:224"
```

**Comment by TritoXid** [comment]
Hi,
I have same issue with this replication from existing cluster.
You can find this variable in config `redis/redis.conf`, but if you use `sed` for overwrite, you get error `Read-only file system`.
Second way is rewrite this slaveof value via `redis-cli`, this working, but after recreate pod, this new value will be lost and you can start from beginning. Next issue what I have is random disconnecting after setup this hack via `redis-cli`. You can see it in next log:

```
# Connection with master lost.
* Caching the disconnected master state.
* Discarding previously cached master state.
* MASTER MODE enabled (user request from 'id=785 addr=<IP>:<PORT> fd=17 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=slaveof')
* SLAVE OF <IP>:<PORT> enabled (user request from 'id=687 addr=<IP>:<PORT> fd=11 name=sentinel-41732aab-cmd age=210 idle=0 flags=x db=0 sub=0 psub=0 multi=3 qbuf=0 qbuf-free=32768 obl=36 oll=0 omem=0 events=r cmd=exec')
# CONFIG REWRITE failed: Permission denied
* Connecting to MASTER <IP>:<PORT>
* MASTER <-> SLAVE sync started
* Non blocking connect for SYNC fired the event.
* Master replied to PING, replication can continue...
* Partial resynchronization not possible (no cached master)
* Full resync from master: <HASH_ID>
* MASTER <-> SLAVE sync: receiving 171 bytes from master
* MASTER <-> SLAVE sync: Flushing old data
* MASTER <-> SLAVE sync: Loading DB in memory
* MASTER <-> SLAVE sync: Finished with success
# Connection with master lost.
```

**Comment by alecjacobs5401** [comment]
FWIW - the dumbest thing that works for me is to
1. Stop the operator from running completely
2. Setup my desired replication chain and let the redis instances catch up on replication
  a. This includes correctly configuring sentinels and the redis instances
3. Point clients to new set of sentinels
4. Force a failover / take old "master" (existing redis instance) out of service
5. Startup the operator again

**Comment by alecjacobs5401** [comment]
Bumping this.

Is there any hesitance or issue with potentially specifying a "bootstrap node" in the `RedisFailover` definition? It would be really convenient to be able to start up a new redis failover that replicates from an existing `RedisFailover` system or even just another pre-existing redis instance outside of the Kubernetes cluster.

The whole "stopping and starting" operators thing works in the mean time, but is really human error prone.

### Potential Config
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  bootstrapNode: some-redis-dns-or-ip:6379
  sentinel:
    replicas: 3
  redis:
    replicas: 3
``
or even
```
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  bootstrapNode:
    host: some-redis-dns-or-ip
    port: 6379  
  sentinel:
    replicas: 3
  redis:
    replicas: 3
``

**Comment by alecjacobs5401** [comment]
Even better probably, while we're in this state and "bootstrapping", we don't even start the Sentinel pods so that this second set of `RedisFailover` redis pods aren't nominated to become new masters in the case of a failover

@ese @chusAlvarez I'm curious to hear your thoughts on this becoming a feature of the operator.

I would be more than happy to put together the PR necessary for this as well.

**Comment by chusAlvarez** [comment]
> Even better probably, while we're in this state and "bootstrapping", we don't even start the Sentinel pods so that this second set of `RedisFailover` redis pods aren't nominated to become new masters in the case of a failover
> 
> @ese @chusAlvarez I'm curious to hear your thoughts on this becoming a feature of the operator.
> 
> I would be more than happy to put together the PR necessary for this as well.

This will be a very useful feature indeed :). Manually migrating currently is a pain and very error-prone.

**Comment by alecjacobs5401** [comment]
Great! I can put together and work a PR soon if thats the case (and no one on your team is actively doing so :) )
