### ISSUE TITLE
Help needed - Unable to deploy redisoperator, how to troubleshoot?

### ISSUE THREAD

**Issue by rajanarayan92** [spotahome/redis-operator#221]
I'm trying to launch the redis-operator on kubernetes v1.13 by executing below command-
kubectl create -f https://raw.githubusercontent.com/spotahome/redis-operator/master/example/operator/all-redis-operator-resources.yaml

But redis-operator pod keeps on crashing. Can someone please help me in troubleshooting the problem?

```
[root@node1 redis_tests]# kubectl create -f https://raw.githubusercontent.com/spotahome/redis-operator/master/example/operator/all-redis-operator-resources.yaml
deployment.apps/redisoperator created
clusterrolebinding.rbac.authorization.k8s.io/redisoperator created
clusterrole.rbac.authorization.k8s.io/redisoperator created
serviceaccount/redisoperator created

[root@node1 redis_tests]# kubectl get deployments.
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
redisoperator   0/1     1            0           4m28s

[root@node1 redis_tests]# kubectl get deployments.
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
redisoperator   0/1     1            0           4m29s

[root@node1 redis_tests]# kubectl get pods -o wide
NAME                            READY   STATUS             RESTARTS   AGE     IP                NODE    NOMINATED NODE   READINESS GATES
redisoperator-b6fc5cf48-n8x9d   0/1     CrashLoopBackOff   5          4m41s   192.168.135.56    node3   <none>           <none>
samplepod                       1/1     Running            0          27d     192.168.226.178   node8   <none>           <none>
```

Also, not able to deploy the redis-failover as well. Below error is seen. Please help!

```
[root@node1 redis_tests]# kubectl create -f https://raw.githubusercontent.com/spotahome/redis-operator/master/example/redisfailover/basic.yaml
error: unable to recognize "https://raw.githubusercontent.com/spotahome/redis-operator/master/example/redisfailover/basic.yaml": no matches for kind "RedisFailover" in version "databases.spotahome.com/v1"
```

**Comment by rajanarayan92** [comment]
Could someone guide me to troubleshoot this problem? Any help would be much appreciated.

**Comment by orbjet** [comment]
Check if you have enough resources on the nodes (CPU/RAM), what do you get from "kubectl describe po redisoperator-b6fc5cf48-n8x9d" ?

**Comment by rajanarayan92** [comment]
Here is the pod output. Seems like there is enough resources on the nodes.

Name:               redisoperator-67b6d78f-cs7h6
Namespace:          development
Priority:           0
PriorityClassName:  <none>
Node:               node1/10.6.55.100
Start Time:         Thu, 30 Jan 2020 04:19:13 -0500
Labels:             app=redisoperator
                    pod-template-hash=67b6d78f
Annotations:        k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "cni0",
                          "ips": [
                              "192.168.169.101"
                          ],
                          "default": true,
                          "dns": {}
                      }]
Status:             Running
IP:                 192.168.169.101
Controlled By:      ReplicaSet/redisoperator-67b6d78f
Containers:
  app:
    Container ID:   docker://944a6270eeeddb6254cadad7a52247babfb356b28a7fa6dc215b7b5e26833bf1
    Image:          quay.io/spotahome/redis-operator:latest
    Image ID:       docker-pullable://quay.io/spotahome/redis-operator@sha256:a008aaadd862132bce225b5b39f6d84b2c5837459823989f2716ddc61ea62fa5
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 30 Jan 2020 04:21:02 -0500
      Finished:     Thu, 30 Jan 2020 04:21:08 -0500
    Ready:          False
    Restart Count:  4
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     50Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from redisoperator-token-c4rrc (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  redisoperator-token-c4rrc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  redisoperator-token-c4rrc
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  2m53s                 default-scheduler  Successfully assigned development/redisoperator-67b6d78f-cs7h6 to node1
  Normal   Pulled     64s (x5 over 2m51s)   kubelet, node1     Container image "quay.io/spotahome/redis-operator:latest" already present on machine
  Normal   Created    64s (x5 over 2m51s)   kubelet, node1     Created container
  Normal   Started    64s (x5 over 2m50s)   kubelet, node1     Started container
  Warning  BackOff    21s (x10 over 2m37s)  kubelet, node1     Back-off restarting failed container
[root@node1 ~]#

**Comment by Yoomtah** [comment]
I'm also experiencing the RedisFailover Specification creation error.

error: unable to recognize ".\\basic.yml": no matches for kind "RedisFailover" in version "databases.spotahome.com/v1"

**Comment by rajanarayan92** [comment]
Following logs are seen - 
```
[root@node1 redis_tests]# kubectl logs redisoperator-6fddbc67cf-scz67 app 
time="2020-02-06T17:12:43Z" level=info msg="Listening on :9710 for metrics exposure" src="asm_amd64.s:1337"
time="2020-02-06T17:12:43Z" level=warning msg="controller name not provided, it should have a name, fallback name to: *redisfailover.RedisFailoverHandler" controller=redisfailover operator=redis-operator src="generic.go:64"
time="2020-02-06T17:12:43Z" level=info msg="starting operator" operator=redis-operator src="main.go:87"
time="2020-02-06T17:12:43Z" level=error msg="Error received: error creating crd redisfailovers.databases.spotahome.com: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:development:redisoperator\" cannot create resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope, exiting..." src="main.go:124"
time="2020-02-06T17:12:43Z" level=info msg="Stopping everything, waiting 5s..." src="main.go:101"
error executing: error creating crd redisfailovers.databases.spotahome.com: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:development:redisoperator" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope

```

What could be the reason for **error msg="Error received: error creating crd redisfailovers.databases.spotahome.com: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:development:redisoperator\" cannot create resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope, exiting..."**

**Comment by rajanarayan92** [comment]
I understand this is not the section to ask such queries, but we are stuck and unable to proceed further. Can someone please help me with identifying what is going wrong here?

**Comment by simonhou** [comment]
@rajanarayan92 Your can try to specify **default** namespace to deploy the operator instead of development.

**Comment by rajanarayan92** [comment]
@simonhou Thanks, that was the issue
