### ISSUE TITLE
[Question] What tag to use instead of 'latest'?

### ISSUE THREAD

**Issue by VassyutovichIlya** [spotahome/redis-operator#225]
Hello. I'm following "the best practice" in terms of not using 'latest'-images. But at https://quay.io/repository/spotahome/redis-operator?tag=latest&tab=tags it is not clear which tag should I use. 

Now I've chosen `89f17c9f6a3ce602b0167a0cf9da26bc636922b0`. But it is very weird to my taste. I need some help with understanding what exactly am I referencing by this tag and, may be, there is a way to use more common approach with exact versions?

**Comment by ese** [comment]
You should use release tags: https://github.com/spotahome/redis-operator/releases
