### ISSUE TITLE
[Question] Plans on supporting redis cluster with sharding

### ISSUE THREAD

**Issue by VassyutovichIlya** [spotahome/redis-operator#230]
Hello. Love your operator, but do you have any plans on implementing [sharding cluster](https://redis.io/topics/cluster-tutorial)?

**Comment by zedtux** [comment]
There are many Redis Cluster operators out there, which are supporting only cluster mode.

This operator is supporting the Master/Slave replication mode (which is completely different from the cluster mode).

In my opinion, this operator shouldn't implement the cluster mode and stick on the Master/Slave replication model with Sentinel.

**Comment by ese** [comment]
We don't have plans at this moment. Our priorities are to improve management. Upgrades, Take and load snapshots, integrate proxy and so on.
