### ISSUE TITLE
timeouts in semi-large gke environments

### ISSUE THREAD

**Issue by hoffoo** [spotahome/redis-operator#231]
### Expected behaviour

Redis timeouts timeouts shouldn't happen

### Actual behaviour

We use the operator in 3 different environments - in our staging env there can be many instances managed by a single operator. 

We have noticed after extended operation the operator will being failing to connect to the redis pods with an i/o timeout

We dont see this issue in our other envs where we only have a few instances running. 

The most odd part is that restarting the operator doesnt fix this, we have to actually restart the orphaned pods. I was tempted to blame the redis lib until discovering this.

Its happens 4-5 times in the past 3 months so its relatively intermittent.

### Steps to reproduce the behaviour

Its really hard to reproduce. Have lots of instances managed by a single operator in gke. 

### Environment

How are the pieces configured?
* Redis Operator version

v1.0.0-rc.2

* Kubernetes version

v1.13.11-gke.14

* Kubernetes configuration used (eg: Is RBAC active?)

RBAC is disabled
Network Policy is enabled but operator has access to everything

### Logs

time="2020-01-29T20:01:14Z" level=debug msg="Setting the custom config on redis 10.24.58.83..." operator=redis-operator src="checker.go:85"
time="2020-01-29T20:01:17Z" level=debug msg="Sentinel is not monitoring the correct master" operator=redis-operator src="handler.go:79"
time="2020-01-29T20:01:17Z" level=debug msg="Sentinel is not monitoring the correct master, changing..." operator=redis-operator src="checker.go:97"
time="2020-01-29T20:01:23Z" level=warning msg="error processing pol-537/redis job (requeued): read tcp 10.24.10.79:60736->10.24.52.145:26379: i/o timeout" controller=redisfailover operator=redis-operator src="generic.go:224"
time="2020-01-29T20:01:24Z" level=info msg="configMap updated" configMap=rfs-redis namespace=pol-482-query-fix service=k8s.configMap src="configmap.go:76"

**Comment by ese** [comment]
Thanks @hoffoo. Could you test with https://github.com/spotahome/redis-operator/releases/tag/v1.0.0-rc.5 ? I'm not sure but it could be related with https://github.com/spotahome/redis-operator/pull/216

**Comment by hoffoo** [comment]
im trying this out, will reopen if i see this again, thanks!
