### ISSUE TITLE
FailedPreStopHook: shutdown.sh exited with 137: , message: ""

### ISSUE THREAD

**Issue by zedtux** [spotahome/redis-operator#236]
### Expected behaviour

I wanted to delete the RedisFailover using `kubectl delete -f ...`

### Actual behaviour

The pod is well destroyed, but I found that error in the events:

```
Exec lifecycle hook ([/bin/sh /redis-shutdown/shutdown.sh]) for Container "redis" in Pod "rfr-redis-0_my-dbs(3413665f-e70f-4a57-bbe5-c1553779f96f)" failed - error: command '/bin/sh /redis-shutdown/shutdown.sh' exited with 137: , message: ""
```

### Steps to reproduce the behaviour

1. You have to enable persistence with the `keepAfterDeletion: true` flag,
2. `kubectl create -f ...`
3. After the cluster is up, `kubectl delete -f ...`

### Environment

How are the pieces configured?
* Redis Operator version v1.0.0-rc.4
* Kubernetes version 
  ```
  Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
  ```
* Kubernetes configuration used (eg: Is RBAC active?)
  RBAC enabled

### Logs

Nothing relevant in the logs.

**Comment by zedtux** [comment]
Yeah, I agree.

**Comment by zedtux** [comment]
Are you smart enough @github-actions to followup with the right guy at spotahome ? THAT would be useful than boring us.

**Comment by timogoosen** [comment]
> Are you smart enough @github-actions to followup with the right guy at spotahome ? THAT would be useful than boring us.

I guess not
