### ISSUE TITLE
no matches for kind "RedisFailover" in version "databases.spotahome.com/v1

### ISSUE THREAD

**Issue by andrewinston** [spotahome/redis-operator#237]
### Expected behaviour

Trying to create a basic CRD with the command 

`kubectl create -f https://raw.githubusercontent.com/spotahome/redis-operator/master/example/redisfailover/basic.yaml
`
I expected it to create the CRD

### Actual behaviour

`error: unable to recognize "https://raw.githubusercontent.com/spotahome/redis-operator/master/example/redisfailover/basic.yaml": no matches for kind "RedisFailover" in version "databases.spotahome.com/v1"
`
### Steps to reproduce the behaviour

I ran 
`kubectl create -f https://raw.githubusercontent.com/spotahome/redis-operator/master/example/operator/all-redis-operator-resources.yaml
`

to create all the necessary resources, but when I tried to run 

`kubectl create -f https://raw.githubusercontent.com/spotahome/redis-operator/master/example/redisfailover/basic.yaml
`
as stated on README.md, I get the above mentioned error

### Environment

How are the pieces configured?
* Redis Operator version: not sure how to acquire this information, it was pulled from master at [this commit](https://github.com/spotahome/redis-operator/commit/11131c841062ddb0b7ea53e98c220ea1e6dc185b)
* Kubernetes version: Output for the command "kubectl version": 
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes configuration used (eg: Is RBAC active?) I don't know.

I should add that there is a redisfailover-redisoperator pod in CrashLoopBackOff with the following logs being output:

`time="2020-02-06T19:36:04Z" level=info msg="Listening on :9710 for metrics exposure" src="asm_amd64.s:1337"
time="2020-02-06T19:36:04Z" level=warning msg="controller name not provided, it should have a name, fallback name to: *redisfailover.RedisFailoverHandler" controller=redisfailover operator=redis-operator src="generic.go:64"
time="2020-02-06T19:36:04Z" level=info msg="starting operator" operator=redis-operator src="main.go:87"
time="2020-02-06T19:36:04Z" level=error msg="Error received: error creating crd redisfailovers.databases.spotahome.com: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:redis-operator:default\" cannot create resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope, exiting..." src="main.go:124"
time="2020-02-06T19:36:04Z" level=info msg="Stopping everything, waiting 5s..." src="main.go:101"
error executing: error creating crd redisfailovers.databases.spotahome.com: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:redis-operator:default" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope`

It is the first time I try to work with operators, and I'm fairly new to Kubernetes, so I apologize for any potential lack of knowledge

**Comment by andrewinston** [comment]
Well, I suspected the problem was related to the image I was pulling, so I changed

> image: quay.io/spotahome/redis-operator:latest
to
> image: quay.io/spotahome/redis-operator:89f17c9f6a3ce602b0167a0cf9da26bc636922b0

And now it seems to be working properly. I don't know exactly the reasons, if anyone could explain me, I'd be glad.

**Comment by PabloL007** [comment]
@andrewinston did you manage to get it working? I have the same issue

**Comment by PabloL007** [comment]
I got it working, I think the issue is not allowing enough time for the operator to boot up and create the CRD (if it has any issues booting up then it won't be created either). So if this is happening to anyone just do the first step, make sure it boots up correctly and creates the resource and then deploy some replicas.

**Comment by iLeonelPerea** [comment]
did you solve it? how?
