### ISSUE TITLE
Switch from StatefulSet to individual Pods

### ISSUE THREAD

**Issue by logdnalf** [spotahome/redis-operator#240]
### Expected behaviour

Using StatefulSets to manage Redis means that it is very hard (if not impossible) to have a subset of the Redis Pods use some configuration and another subset a different configuration. Example: A/B testing where half of the Redis replicas run version X and the other half run version X+1 for some period of time.

It would be nice if the Redis Operator works by setting up individual Pods, not connected to any StatefulSet. The Operator watches and babysits them pretty much as the StatefulSet. I understand that this increases complexity but it is beneficial in production, in my opinion.

### Actual behaviour

Using StatefulSet to deploy Redis makes it impossible to have Pods use different configuration attributes (from the YAML spec).

**Comment by cameronbraid** [comment]
This is how https://github.com/banzaicloud/kafka-operator does it too, and their design motivations explains why https://github.com/banzaicloud/kafka-operator/blob/master/docs/features.md
