### ISSUE TITLE
cannot deploy failovers 

### ISSUE THREAD

**Issue by SCLogo** [spotahome/redis-operator#241]
### Expected behaviour
Using the examples, able to deploy basic.yaml

### Actual behaviour
no matches for kind "RedisFailover" in version "databases.spotahome.com/v1

### Steps to reproduce the behaviour

kubectl create -f https://raw.githubusercontent.com/spotahome/redis-operator/master/example/redisfailover/basic.yaml

**Comment by sprinkaan88** [comment]
Having the same issue when installing via Helm.
The types have completely different names.
Want to get metrics exposed, not sure how to do it without Helm since that is the only place I see the options.

**Comment by foogass** [comment]
have the same issue, cluster version is 1.15.12

**Comment by jsalatiel** [comment]
Anyone able to fix it ?
