### ISSUE TITLE
Use the same sentinels to monitor multiple master/slave replica sets?

### ISSUE THREAD

**Issue by wilsonlindelof** [spotahome/redis-operator#244]
Hey all, I tried looking for this in the docs but couldn't find an answer. I would like to use the same sentinels to monitor multiple master/slave replica sets to reduce the number of pods needed for each unique redis store instance. 

Right now, with the basic.yaml config, it takes 7 pods (1 operator, 3 sentinels, and 3 replicas) per unique store, if I do another helm install to create the operator. I can get it down to 6 pods by using the same operator but creating another specification under it. What I am looking for though and I cant find any example configs for is to be able to use the same sentinels on different specifications, so that I could have 1 operator, 3 sentinels, and say 3 sets of 3 replicas, all being monitored by the same sentinels. 

Is this feature supported? Does anyone have a sample config that accomplishes this?

**Comment by emillg** [comment]
I am also looking for multiple master/slave replica sets support.
