### ISSUE TITLE
The operator is constantly updating resources (each ~ 30 seconds)

### ISSUE THREAD

**Issue by zedtux** [spotahome/redis-operator#246]
### Expected behaviour

The operator should update the resources when it is required.

### Actual behaviour

Looking at the operator logs, I see plenty of "updates" each 30 seconds which makes [kubewatch](https://github.com/bitnami-labs/kubewatch) sending a lot of notifications about deployment updates:

```
time="2020-03-02T11:51:02Z" level=info msg="configMap updated" configMap=rfs-redis namespace=dbs service=k8s.configMap src="configmap.go:76"
time="2020-03-02T11:51:02Z" level=info msg="configMap updated" configMap=rfr-s-redis namespace=dbs service=k8s.configMap src="configmap.go:76"
time="2020-03-02T11:51:02Z" level=info msg="configMap updated" configMap=rfr-readiness-redis namespace=dbs service=k8s.configMap src="configmap.go:76"
time="2020-03-02T11:51:02Z" level=info msg="configMap updated" configMap=rfr-redis namespace=dbs service=k8s.configMap src="configmap.go:76"
time="2020-03-02T11:51:02Z" level=info msg="podDisruptionBudget updated" namespace=dbs podDisruptionBudget=rfr-redis service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2020-03-02T11:51:02Z" level=info msg="statefulSet updated" namespace=dbs service=k8s.statefulSet src="statefulset.go:101" statefulSet=rfr-redis
time="2020-03-02T11:51:02Z" level=info msg="podDisruptionBudget updated" namespace=dbs podDisruptionBudget=rfs-redis service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2020-03-02T11:51:02Z" level=info msg="deployment updated" deployment=rfs-redis namespace=dbs service=k8s.deployment src="deployment.go:101"


time="2020-03-02T11:51:32Z" level=info msg="configMap updated" configMap=rfs-redis namespace=dbs service=k8s.configMap src="configmap.go:76"
time="2020-03-02T11:51:32Z" level=info msg="configMap updated" configMap=rfr-s-redis namespace=dbs service=k8s.configMap src="configmap.go:76"
time="2020-03-02T11:51:32Z" level=info msg="configMap updated" configMap=rfr-readiness-redis namespace=dbs service=k8s.configMap src="configmap.go:76"
time="2020-03-02T11:51:32Z" level=info msg="configMap updated" configMap=rfr-redis namespace=dbs service=k8s.configMap src="configmap.go:76"
time="2020-03-02T11:51:33Z" level=info msg="podDisruptionBudget updated" namespace=dbs podDisruptionBudget=rfr-redis service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2020-03-02T11:51:33Z" level=info msg="statefulSet updated" namespace=dbs service=k8s.statefulSet src="statefulset.go:101" statefulSet=rfr-redis
time="2020-03-02T11:51:33Z" level=info msg="podDisruptionBudget updated" namespace=dbs podDisruptionBudget=rfs-redis service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2020-03-02T11:51:33Z" level=info msg="deployment updated" deployment=rfs-redis namespace=dbs service=k8s.deployment src="deployment.go:101"
```

What is happening is that my app gets some `No sentinels available.` error.

### Steps to reproduce the behaviour

Deploy the operator and a RedisFailover and tail the operator's logs

### Environment

How are the pieces configured?
* Redis Operator version: `1.0.0`
* Kubernetes version: `1.15.4`
* Kubernetes configuration used: RBAC is active

**Comment by MDrollette** [comment]
I'm curious about this as well. Is it intended behavior?

**Comment by Kampe** [comment]
Can we turn this off?

**Comment by zedtux** [comment]
Thank you bot, really useful 👍

**Comment by zedtux** [comment]
Yeah, nice catch bot @github-actions, like always ! Feel free to remind the spotahome guys 😉

**Comment by sreejithsoman-mc** [comment]
@zedtux were you able to resolve this issue

**Comment by zedtux** [comment]
Nope @sreejithsoman-mc

**Comment by sreejithsoman-mc** [comment]
@zedtux how did you manage then ? replaced with some other operator?

**Comment by zedtux** [comment]
Unfortunately I've removed kubewatch

**Comment by sreejithsoman-mc** [comment]
@zedtux  ok , So in spite of this messages , redisfailover is working perfectly?

**Comment by zedtux** [comment]
> redisfailover is working perfectly

Well, I have broke the cluster 2 - 3 times in 2 years, mainly because of myself (I'm learning to be more and more patient when working on Kubernetes).

In another project, running out of Kubernetes (which doesn't matter here), I've made a Slack notification script (in Bash) to monitor a Redis/Sentinel cluster, which give us a good understanding of the state of the state of each members, and of the cluster itself. (I have to add that script to all my projects running on Kubernetes!).
I made that script 4 months ago, so I can say I begin to know a little bit how good is working the Redis' failover and I can say it really rocks when you've fine tuned the cluster's config ! (The election takes literally 2 seconds :+1:).
And I guess it works the same in Kubernetes.

One thing I can share with you to avoid to break your Redis cluster : force an election when you need to take down the master node/container !
When I need to reboot the node (new Linux Kernel), I can execute the `reboot` command on all the nodes without breaking anything excepted for the current master node. When I need to reboot the master node, I stop the Redis and the Sentinel services, wait for the detection timeout and the election, and then I reboot the node.
That way, the cluster survives the nodes reboot.

I hope this give you a quick look at Redis failover.

**Comment by sreejithsoman-mc** [comment]
@zedtux Thanks for the detailed response. So in your opinion the update messages from operator can be ignored? Is this an expected behavior?

**Comment by zedtux** [comment]
Well, no, I would say you have to go with Prometheus/AlertManager. It's a really great piece of software and you will be able to be alerte about anything that happen in your cluster, and even predict issues ! You have to build your queries, but when you master it, you're like Sauron in Kubernetes 😂
