### ISSUE TITLE
Operator multiple replicas

### ISSUE THREAD

**Issue by gargath** [spotahome/redis-operator#252]
### Expected behaviour

redis-operator helm chart and example `Deployment` should either
a) use more than one replica
or
b) have documentation indicating that a single-replica `Deployment` is strictly required

### Actual behaviour

Both helm chart and example YAML have a hard coded `replicas: 1` without the documentation specifying whether this is a functional requirement or not.

### Background

We tend to deploy operators and controllers as pairs of two (or more) replicase so that there is no gap in coverage when losing or replacing the node running the operator `Pod`.
The use of a hard-coded `replicas: 1` in the helm chart along with a lack of leadership-election settings makes me suspect that the redis-operator currently can only run as a single-replica deployment, but can't verify either way.

**Comment by Wouter0100** [comment]
Leader election was introduced in #438. I updated the Helm chart in #492.
