### ISSUE TITLE
using save "" in customConfig breaks redis-operator

### ISSUE THREAD

**Issue by nextsux** [spotahome/redis-operator#262]
### Expected behaviour

I was trying to disable persistence on redis using customConfig:
```
spec:
  redis:
    customConfig:
    - save ""
```

### Actual behaviour
Redis operator fails to configure redis using config set with errors like:
```
[redis-operator-redisoperator-75785dc7c7-cmtgq] time="2020-05-08T11:08:16Z" level=warning msg="error processing kuki-redis/sentinel job (requeued): ERR Invalid argument '\"\"' for CONFIG SET 'save'" controller=redisfailover operator=redis-operator src="generic.go:224" 
```

Redis operator fails to correctly escape/unescape quote characters which are important for save command when you need to signalize empty string

I think it may be the reason of #95

**Comment by danielllek** [comment]
I've hit the same problem.

**Comment by alecjacobs5401** [comment]
There is a workaround that you can put in place (that Isn't pretty) by overriding the container command in the `redis` definition:
```
command: ["redis-server", "/redis/redis.conf", "--save", ""]
```

Agreed, though, that this should be configurable in the custom config
