### ISSUE TITLE
Add ability to set resource requests and limits for redis-exporter container

### ISSUE THREAD

**Issue by leejones** [spotahome/redis-operator#266]
### Expected behaviour

I'd like to be able to define the resource requests and limits for the `redis-exporter` container. Specifically, I'd like to disable the CPU limit since it can lead to [excessive throttling](https://medium.com/omio-engineering/cpu-limits-and-aggressive-throttling-in-kubernetes-c5b20bd8a718).

### Actual behaviour

The [defaults](https://github.com/spotahome/redis-operator/blob/79009d8d53e57f15593213c119caad029813bd04/operator/redisfailover/service/constants.go#L15-L18) are used.

**Comment by PetzJohannes** [comment]
Is anybody working on this issue or is this project dead?

**Comment by n1kk0** [comment]
@joewreschnig, maybe you could just make a Pull Request from your repository and see where it goes :) .

Just saying, because the currently extremely low resources of the exporter makes this controller really hard to use in production since the false positive alerts are flooding.
