### ISSUE TITLE
Feature Request: TLS Support for redis 6

### ISSUE THREAD

**Issue by ankur-anand** [spotahome/redis-operator#268]
Hi,

Currently, the operator doesn't support the mounting of a path for the TLS file or through any Kubernetes secret.

Redis 6 supporting TLS, needs the path of the TLS file in the configuration.

Is there any plan to support the Redis 6 TLS configuration?

 Thanks.

**Comment by dejwsz** [comment]
I am interested too. I think this is a very important feature in many production use cases where you have to provide a very secure environment.

**Comment by kevinlmadison** [comment]
I am also interested in this. Very important feature for our cluster!

**Comment by ccravens** [comment]
+1 for this feature request!

**Comment by dejwsz** [comment]
looks like another redis operator has support for TLS: https://github.com/OT-CONTAINER-KIT/redis-operator
