### ISSUE TITLE
Master name should be name of k8s resource, not "mymaster"

### ISSUE THREAD

**Issue by Hades32** [spotahome/redis-operator#274]
The magic value of "mymaster" is highly unintuitive.

It would be much nicer if this could be configured or default to the name of the declared resource. Declaring the name of the master is an extra fail-safe mechanism and having it be the same for all instances renders this mechanism obsolete.

**Comment by k3daevin** [comment]
Why not just make the Master name configurable in the k8s resource with default value "mymaster" (or the k8s resource).
