### ISSUE TITLE
How to disable Sentinel and allow single node Redis (or even one master and multiple followers in some way)

### ISSUE THREAD

**Issue by brucemei** [spotahome/redis-operator#284]
when i apply the master(replicas) **1** and sentinel(replicas) **0**.

It seems strange that the sentinel pods **3** running (master pods 1)

**Comment by Manicben** [comment]
Hey, if you look at https://github.com/spotahome/redis-operator/blob/master/api/redisfailover/v1/validate.go, you can see that if Sentinel is not specified or set to 0 replicas, the validation method will ensure it is set to the default value, which is 3. This implies that the operator will block us from disabling Sentinel entirely.

I would recommend you rename your issue to request being able to disable Sentinel and allow single node Redis (or even one master and multiple followers in some way). This is a feature my benefactors and I be extremely interested in too.

**Comment by brucemei** [comment]
> Hey, if you look at https://github.com/spotahome/redis-operator/blob/master/api/redisfailover/v1/validate.go, you can see that if Sentinel is not specified or set to 0 replicas, the validation method will ensure it is set to the default value, which is 3. This implies that the operator will block us from disabling Sentinel entirely.
> 
> I would recommend you rename your issue to request being able to disable Sentinel and allow single node Redis (or even one master and multiple followers in some way). This is a feature my benefactors and I be extremely interested in too.

thanks for your key suggestion
