### ISSUE TITLE
Problem running the failover

### ISSUE THREAD

**Issue by Kyrremann** [spotahome/redis-operator#29]
I'm new to k8s and operators, and I'be been trying to get the redis-operator working, but it seems stuck in starting up the sentinels. At least I can't get my pod connecting to a redis instance.

I've made a `operator.yaml` with the code from the README.md, and a `failover.yaml` with the code from the same file. The operator pod (with two containers) starts up correct, but I'm having problems with the failover. I did a small update to the `operator.yaml`, so that I'm using the latest image, and not the old one specified in the example.

The main pod starts up, but the sentinels (not 100% sure that's what they are?) are stuck in `Init:0/1` statte.

`kubectl get pods` looks like this.
```
NAME                                   READY     STATUS     RESTARTS   AGE
redisoperator-d9f6f5fff-zwfnl          1/1       Running    0          1h
rfb-myredisfailover                    2/2       Running    0          11m
rfs-myredisfailover-65788fd777-2g4kv   0/1       Init:0/1   0          11m
rfs-myredisfailover-65788fd777-46cr8   0/1       Init:0/1   0          11m
rfs-myredisfailover-65788fd777-xnn25   0/1       Init:0/1   0          6m
```

I'm pretty sure I'm missing something, but can't find out what. On thing I think is strange is that the main failover pod is named `rf*b*-my...`, and not `rf*s*-my...`, same as the other failover containers.

Any help would be appreciated.

**Comment by jchanam** [comment]
Hi @Kyrremann!

First of all, thanks for trying the operator! :+1: 

A little bit of explanation about the notation:
* rfb -> bootstrap
* rfs -> sentinel
* rfr -> redis

It seems that the sentinels are stucked on the initialisation process, this could be happening because they are not able to connect to the bootstrap-pod.

Could you please check the sentinel service is created and has endpoints on it?
Could you give me the logs for the init container of the sentinels?

Apart from that, we've just done a huge refactor of the code, making it much easier. Would you like to give it a try?

**Comment by Kyrremann** [comment]
Thanks for the quick reply.

The sentinel service is made:
`rfs-myredisfailover   ClusterIP   10.110.15.45   <none>        26379/TCP   39m`

```
$k get service rfs-myredisfailover -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-02-19T15:12:36Z
  labels:
    app: redis-failover
    component: sentinel
    sentinel: myredisfailover
  name: rfs-myredisfailover
  namespace: default
  resourceVersion: "3842"
  selfLink: /api/v1/namespaces/default/services/rfs-myredisfailover
  uid: 515bcf1a-1587-11e8-abf3-2e3351cf85de
spec:
  clusterIP: 10.110.15.45
  ports:
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: 26379
  selector:
    app: redis-failover
    component: sentinel
    sentinel: myredisfailover
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Same with the endpoints:
`rfs-myredisfailover   172.17.0.6:26379     40m`
```
$ k get endpoints rfs-myredisfailover -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2018-02-19T15:12:36Z
  labels:
    app: redis-failover
    component: sentinel
    sentinel: myredisfailover
  name: rfs-myredisfailover
  namespace: default
  resourceVersion: "4113"
  selfLink: /api/v1/namespaces/default/endpoints/rfs-myredisfailover
  uid: 515ca4e9-1587-11e8-abf3-2e3351cf85de
subsets:
- addresses:
  - ip: 172.17.0.6
    nodeName: minikube
    targetRef:
      kind: Pod
      name: rfb-myredisfailover
      namespace: default
      resourceVersion: "3839"
      uid: 4265ea29-1587-11e8-abf3-2e3351cf85de
  notReadyAddresses:
  - ip: 172.17.0.10
    nodeName: minikube
    targetRef:
      kind: Pod
      name: rfs-myredisfailover-65788fd777-xnn25
      namespace: default
      resourceVersion: "4112"
      uid: 09510460-1588-11e8-abf3-2e3351cf85de
  - ip: 172.17.0.7
    nodeName: minikube
    targetRef:
      kind: Pod
      name: rfs-myredisfailover-65788fd777-2g4kv
      namespace: default
      resourceVersion: "3889"
      uid: 5465c2ad-1587-11e8-abf3-2e3351cf85de
  - ip: 172.17.0.8
    nodeName: minikube
    targetRef:
      kind: Pod
      name: rfs-myredisfailover-65788fd777-46cr8
      namespace: default
      resourceVersion: "3895"
      uid: 54670248-1587-11e8-abf3-2e3351cf85de
  ports:
  - name: sentinel
    port: 26379
    protocol: TCP
```

Not sure which one is the init container for the sentinels, but I see that the bootstrap pod has a sentinel container in it.

```
$ k logs rfb-myredisfailover -c sentinel
Attempting to connect to Sentinel service to retrieve current master...
Could not connect to Redis at -p:6379: Try again
Got ''
FAILED
Attempting to connect to Master at 172.17.0.6...
OK
<removed the asci art>
Redis 3.2.11 (00000000/0) 64 bit
Running in sentinel mode
Port: 26379
PID: 14
14:X 19 Feb 15:12:26.417 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
14:X 19 Feb 15:12:26.419 # Sentinel ID is 8162ffff8425c67b1d846a737a69888a02184bfc
14:X 19 Feb 15:12:26.419 # +monitor master mymaster 172.17.0.6 6379 quorum 2
14:X 19 Feb 15:25:39.757 # +tilt #tilt mode entered
14:X 19 Feb 15:26:09.767 # -tilt #tilt mode exited
14:X 19 Feb 15:50:05.052 # +tilt #tilt mode entered
14:X 19 Feb 15:50:35.093 # -tilt #tilt mode exited
```

I saw the PR, and I can test the new code.

**Comment by jchanam** [comment]
Hi!

I see that the service has a ready endpoint, which is the spected state (the IP should match with the bootstrap pod).

To debug what it's happening, I need the logs from the init container on the pod (for example) `rfs-myredisfailover-65788fd777-2g4kv`. I don't know if it's a problem of the connection with the redis on the bootstrap pod or another thing.

If you want to test the new and simplified version, checkout the latest release: https://github.com/spotahome/redis-operator/releases/tag/0.2.0

Thanks!

**Comment by Kyrremann** [comment]
I can't get logs for it, as they haven't started yet.
```
$ k logs rfs-myredisfailover-65788fd777-2g4kv
Error from server (BadRequest): container "sentinel" in pod "rfs-myredisfailover-65788fd777-2g4kv" is waiting to start: PodInitializing
```

Also, the endpoint ip/port is matching the ip of the bootstrap pod and the container port.

I'll give the new version a try!

**Comment by jchanam** [comment]
If you do a `kubectl describe pod`, you can see that there are an init-container. To get it's logs, you can do a `kubectl logs <pod-name> -c <container-name>`

It seems a failure on gathering the master information from the sentinel. You could try to restart the bootstrap-pod :)

**Comment by Kyrremann** [comment]
The pod `rfs-myredisfailover-65788fd777-2g4kv` has only one container in it, and no log since it hasn't started.

The `redisoperator-d9f6f5fff-zwfnl` pod has one container, that first logged this:
```
time="2018-02-19T15:29:38Z" level=debug msg="Waiting for Sentinel deployment to be fully operative" namespace=default redisfailover=myredisfailover src="waiter.go:64"
time="2018-02-19T15:29:38Z" level=debug msg="Maximum threads reached, waiting..." src="controller.go:401"
time="2018-02-19T15:29:39Z" level=debug msg="Maximum threads reached, waiting..." src="controller.go:401"
time="2018-02-19T15:29:40Z" level=debug msg="Maximum threads reached, waiting..." src="controller.go:401"
time="2018-02-19T15:29:41Z" level=debug msg="Maximum threads reached, waiting..." src="controller.go:401"
time="2018-02-19T15:29:42Z" level=debug msg="Maximum threads reached, waiting..." src="controller.go:401"
```

But, after I replaced the `rfb-myredisfailover` pod, it now logs this:
```
time="2018-02-19T17:32:12Z" level=debug msg="Getting mutex for default-myredisfailover from mutex array" src="controller.go:389"
time="2018-02-19T17:32:12Z" level=debug msg="RedisFailover myredisfailover in namespace default is not Ready, skipping" namespace=default redisfailover=myredisfailover src="controller.go:73"
``` 

The last pod, `rfb-myredisfailover`, has two containers, `redis` and `sentinel`.

```
$ k logs rfb-myredisfailover -c redis
1:C 19 Feb 17:24:08.722 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
<removed asci cube>
1:M 19 Feb 17:24:08.723 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 19 Feb 17:24:08.723 # Server started, Redis version 3.2.11
1:M 19 Feb 17:24:08.723 * The server is now ready to accept connections on port 6379
```

And the other one:
```
$ k logs rfb-myredisfailover -c sentinel
Attempting to connect to Sentinel service to retrieve current master...
Could not connect to Redis at -p:6379: Try again
Got ''
FAILED
Attempting to connect to Master at 172.17.0.6...
OK
<removed asci cube>
17:X 19 Feb 17:24:20.456 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
17:X 19 Feb 17:24:20.459 # Sentinel ID is 89d2ca0c386053eff8549bd02a96e8de3b748105
17:X 19 Feb 17:24:20.459 # +monitor master mymaster 172.17.0.6 6379 quorum 2
```

Hope any of this helps.
Havn't tried the `0.2.0` yet. So I can give you more data on the current setup first.

**Comment by Kyrremann** [comment]
Tried the new version (`0.2.0`), and all the pods are up and running now! Not sure if it's worth finding out what was wrong with the old setup.

Hopefully I'll be able to connect to the Redis cluster now.

**Comment by Kyrremann** [comment]
I'm still having issues connecting to the cluster.
These are the `envs` that get injected into my pod:
```
RFS_MYREDISFAILOVER_PORT=tcp://10.100.165.72:26379
RFS_MYREDISFAILOVER_PORT_26379_TCP=tcp://10.100.165.72:26379
RFS_MYREDISFAILOVER_PORT_26379_TCP_ADDR=10.100.165.72
RFS_MYREDISFAILOVER_PORT_26379_TCP_PORT=26379
RFS_MYREDISFAILOVER_PORT_26379_TCP_PROTO=tcp
RFS_MYREDISFAILOVER_SERVICE_HOST=10.100.165.72
RFS_MYREDISFAILOVER_SERVICE_PORT=26379
RFS_MYREDISFAILOVER_SERVICE_PORT_SENTINEL=26379
```

Setting up the connection with the following line:
`r = Redis.new(url: "redis://10.100.165.72:26379")`

gives me `Redis::CommandError (ERR unknown command 'set')` when I try to communicate with it.

Trying to use sentinels:
```
sentinels = [{ host: "10.100.165.72", port: 26379 }]
r = Redis.new("redis://10.100.165.72:26379", sentinels: sentinels)
```

And then I get this error:
`Redis::CannotConnectError (No sentinels available.)`

So what I'm thinking is that the `ENV` that gets injected, is pointing to the master, but I should instead had a list of sentinels to connect to? Is that correct?

**Comment by Kyrremann** [comment]
Okay, never mind the last comment. I had misunderstood the `url` part.

The correct (in Ruby and redis-rb) is to use `redis://mymaster` as the `url`.
```
r = Redis.new(url: "redis://mymaster", sentinels: [{host: "10.100.165.72", port: 26379}])
```

I found the master `name` in the logs for the `rfs`-pods.

Thanks for all the help!

**Comment by ese** [comment]
Thanks for the report @Kyrremann We highly encourage to try with `0.2.0` since we did a deep refactor and we are not gonna make changes on `0.1.x` branch so its deprecated

**Comment by jchanam** [comment]
@Kyrremann As it's working for you now, I'm closing this issue.

If you find anything else failing or you need assistance, please don't hesitate to open a new one.

Thanks!
