### ISSUE TITLE
Fails to create bootstrap-pod when resource quotas enabled.

### ISSUE THREAD

**Issue by nabadger** [spotahome/redis-operator#3]
Hi, 

Thanks for this - looks really promising.

I tried this on our cluster which has resource-quotas enforced and it fails with the following:

> Could not create bootstrap pod: pods "rfb-redis" is forbidden: failed quota: default: must specify limits.cpu,limits.memory,requests.cpu,requests.memory namespace=examples redisfailover=redis src="controller.go:154"

It looks like `CreateBootstrapPod` in controller.go doesn't specify any quotas. Is it possible to make this configurable?

**Comment by jchanam** [comment]
Hi @nabadger,

By default, the operator doesn't set any quota to the elements created. Have you tried defining the resources when creating the redisfailover? If doing so, it also fails?

**Comment by jchanam** [comment]
Sorry, I've misunderstood you. I'll check the best way of doing this. Thanks!

**Comment by jchanam** [comment]
@nabadger There's a new image released with this changes: quay.io/spotahome/redis-operator:0.1.1

Hope this fix the problem you encountered and now you are able to use it.

Thanks for the issue!

**Comment by nabadger** [comment]
@jchanam thanks for this.

I've tried the 0.1.1 image, but get the same issue (on the same line number). Would you be able to confirm that 0.1.1 has the fix pushed?

In the meantime I'll see if I can build an image from src and try that :)

Here's my deployment yaml for the RedisFailover
~~~~
apiVersion: spotahome.com/v1alpha1
kind: RedisFailover
metadata:
  name: redis
  namespace: examples
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        memory: 150Mi
        cpu: 200m
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 200Mi
    exporter: true
~~~~

**Comment by jchanam** [comment]
You're right. The image is upload correctly now. Please try again :)

Sorry for the problems
