### ISSUE TITLE
Sentinel Auth

### ISSUE THREAD

**Issue by nishaad78** [spotahome/redis-operator#302]
### Expected behaviour
When `spec.auth.secretPath` is set, password should be applied to both redis and sentinels.

What do you want to achieve?
I want to have authentication for both the redis servers and sentinels.

### Actual behaviour

When the fix for #66 was implemented in #186, only the redis server had the auth config set in `/redis/redis.conf`
There is no `requirepass` config set in sentinel's `/redis/sentinel.conf`

**Comment by rayanebel** [comment]
Hi,

Any update in this issue ? I can confirm that sentinel does not have authentication enabled _(only redis instance)_. So, when we try to connect by using sentinel service we can connect without any password.

**Comment by ktzsolt** [comment]
@nishaad78 could you reopen this issue? I am also interested in this, Thanks!

**Comment by chobostar** [comment]
Also it writes unencrypted password to ConfigMap:
```
$ kubectl get cm rfr-redisfailover -o yaml
apiVersion: v1
data:
  redis.conf: |-
    slaveof 127.0.0.1 6379
    tcp-keepalive 60
    save 900 1
    save 300 10

    masterauth kugha3shee5Eith4
    requirepass kugha3shee5Eith4
```

**Comment by vanyasvl** [comment]
Please reopen it, problem is still exists. You can connect without password even with auth enabled

**Comment by drivebyer** [comment]
I think there is no need to set sentinel with authentication, becouse we can't get any data from sentinel as far as I know.

**Comment by vanyasvl** [comment]
> I think there is no need to set sentinel with authentication, becouse we can't get any data from sentinel as far as I know.

But we can send control commands to Sentinel and down a cluster

**Comment by drivebyer** [comment]
> But we can send control commands to Sentinel and down a cluster
Emm... it's the case:).

**Comment by martivo** [comment]
So if that is the case, then please reopen the issue.

**Comment by marguspeet** [comment]
+1

**Comment by Miracle05** [comment]
+1

**Comment by zhaidarbek** [comment]
+1
