### ISSUE TITLE
Is there any solution to populate data into to the Redis from external database

### ISSUE THREAD

**Issue by kalpanathanneeru** [spotahome/redis-operator#309]
**What do you want to achieve?**

While bringing up redis instances data should be populated from the external Database.
So after the redis server is up and ready what ever the data on the database should be available on the redis as well.

Any solutions for it?

**Redis Cluster details:**
Deployment type: Sentiel Redis
Redis version : 5.0.3
Platform: Kubernetes (1.20.0)
Storage : PVC

**Comment by ese** [comment]
Hi you can get the data from other instances with bootstrap option https://github.com/spotahome/redis-operator#bootstrapping-from-pre-existing-redis-instances
