### ISSUE TITLE
Feature Request: Allow deploy in multi k8s clusters

### ISSUE THREAD

**Issue by absolute8511** [spotahome/redis-operator#310]
Is there any plan to support deploy one Redis master-slave cluster across multi K8S clusters so we can failover to a different cluster?

Users may want to deploy multi Redis slaves in different regions or across multiple data centers. However, due to various reasons, e.g. network latency, they can not deploy one Kubernetes cluster across multiple regions or data centers. Any plan to provide a way to deploy Redis master in one K8S cluster and deploy multi slaves in different Kubernetes clusters?

**Comment by dipeshtripathi** [comment]
Im surprised this doesn't interest a lot of people.. Where I believe it is essential for a distributed redis..

**Comment by drivebyer** [comment]
In a multi-cluster environment with Kubernetes (k8s), cross-cluster disaster recovery is necessary. For Redis, it is also essential to achieve cross-cluster failover.
