### ISSUE TITLE
Slaves with 127.0.0.1 IP address when running with istio sidecar injection

### ISSUE THREAD

**Issue by kmcrawford** [spotahome/redis-operator#312]
### Expected behaviour

Slaves should show pod IP address vs 127.0.0.1 when running `info replication`

### Actual behaviour

The below occurs when running with istio sidecar injection:
```
/data $ redis-cli
127.0.0.1:6379> info replication
# Replication
role:master
connected_slaves:2
slave0:ip=127.0.0.1,port=6379,state=online,offset=638056607512,lag=1
slave1:ip=127.0.0.1,port=6379,state=online,offset=638056607651,lag=1
```

The above issue causing problems when attempting doing a fail over `NOGOODSLAVE No suitable replica to promote`

### Steps to reproduce the behaviour

Stand up a Redis in a cluster namespace with istio sidecar injection turned on.

I have a work around for this issue but it's not very elegant. 

I have found that this can be solved by setting `replica-announce-ip` to the pod's ipaddress.  However I have had a hard time doing that as I have don't have many options to inject.

I have tried to update the command section as follow:
```
  command:
      - redis-server
      - /redis/redis.conf 
      - --replica-announce-ip 
      - $(hostname -i)
```
This unfortunately this put the literal `"$(hostname -i)"` in the config when I attempted to verify using `CONFIG GET *` command.

The only solution I found was updating my "shutdown.sh" to have a startup condition:

```
data:
  shutdown.sh: |
    #!/bin/sh
    if [[ $1 == "startup" ]]
    then
      redis-server /redis/redis.conf --replica-announce-ip "$(hostname -i)"
    else
      echo "shutdown in progress..."
...
```

Then update my command to call the shutdown.sh passing a startup parameter:

```
  command:
      - /bin/sh
      - /redis-shutdown/shutdown.sh
      - startup
```

This does fix the issue but there should be a more elegant solution to do this, but I have not been successful.

Istio issue where `replica-announce-ip` is referenced.
https://github.com/istio/istio/issues/16078

**Comment by heilerich** [comment]
For anyone stumbling upon this issue: This can be achieved without the shutdown script by simply adding the following `.spec.redis.command` setting to the `RedisFailover` resource.
```yaml
command:
- /bin/sh
- -c
- redis-server /redis/redis.conf --replica-announce-ip "$(hostname -i)"
```
