### ISSUE TITLE
Is this project still under maintenance?

### ISSUE THREAD

**Issue by fantastic2085** [spotahome/redis-operator#315]
### Expected behaviour

What do you want to achieve?

### Actual behaviour

What is happening? Are all the pieces created? Can you access to the service?

### Steps to reproduce the behaviour

Describe step by step what you've have done to get to this point

### Environment

How are the pieces configured?
* Redis Operator version
* Kubernetes version
* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.

**Comment by ese** [comment]
Hi! Currently, we have much fewer resources to dedicate to the project and it has been halted for about one year.
At least we are still using it in production and committed to resolving bugs and issues we face and of course open to receive pull requests, we will be more careful with contributors. 
Probably for the end of the year, we will update underlying components to match with the latest releases of Kubernetes but we are not planning to add features for the moment.
