### ISSUE TITLE
Redis 6 ACL support

### ISSUE THREAD

**Issue by adamkissvcc** [spotahome/redis-operator#319]
Hello!

Is there a plan to add support for configuring ACL? https://redis.io/topics/acl
Or is there already a way to make the operator create users? (customConfig does not work for this)

**Comment by ccravens** [comment]
+1 on this request :)

**Comment by kevinlmadison** [comment]
+1

**Comment by TonyBogdanov** [comment]
+1

**Comment by samof76** [comment]
+1
