### ISSUE TITLE
When's the next release?

### ISSUE THREAD

**Issue by inductor** [spotahome/redis-operator#332]
### Expected behaviour

It seems like it has been a while since 1.0.0 release. When would there be a next release?

### Actual behaviour

What is happening? Are all the pieces created? Can you access to the service?

### Steps to reproduce the behaviour

Describe step by step what you've have done to get to this point

### Environment

How are the pieces configured?
* Redis Operator version
* Kubernetes version
* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.

**Comment by ese** [comment]
Probably next week
