### ISSUE TITLE
standard_init_linux.go:178: exec user process caused "exec format error

### ISSUE THREAD

**Issue by mkamalkayani** [spotahome/redis-operator#336]
Sharing incase someone else also faces this error.

The operator pod failed to run.

The redis-operator pod logs contained the followind error: 
`standard_init_linux.go:178: exec user process caused "exec format error"`

### Solution

The docker image used by the operator is only built for `amd64`.
This command can be used to get the supported platform currently supported by the redis-operator image: 
`docker manifest inspect --verbose quay.io/spotahome/redis-operator`

So, for other architectures, such as in my case `arm64`, the image has to be built.

I used this command to build it for `arm64`
`docker buildx build --platform linux/arm64 --tag mkamalkayani/redis-operator-arm64 .`

and then I pushed this image to docker registry, used this image in the operator.yaml file and reployed the opeator.yaml.

Finally, the pod was up and running.

**Comment by ese** [comment]
Support for arm64 would be great, I would take a look thanks
