### ISSUE TITLE
Creation using example operator deployment and example failover spec fails

### ISSUE THREAD

**Issue by tanner-bruce** [spotahome/redis-operator#34]
I deployed the operator using the sample spec, and used the sample failover as well. The only thing I changed was enabling the metrics exporter

```time="2018-03-13T14:57:14Z" level=info msg="Listening on :9710 for metrics exposure" src="asm_amd64.s:2337"
time="2018-03-13T14:57:14Z" level=info msg="starting operator" operator=redisfailover src="operator.go:99"
time="2018-03-13T14:57:14Z" level=info msg="crd redisfailovers.storage.spotahome.com created, waiting to be ready..." service=k8s.crd src="crd.go:118"
time="2018-03-13T14:57:16Z" level=info msg="crd redisfailovers.storage.spotahome.com ready" service=k8s.crd src="crd.go:120"
time="2018-03-13T14:57:16Z" level=info msg="operator initialized" operator=redisfailover src="operator.go:85"
time="2018-03-13T14:57:16Z" level=info msg="starting controller" controller=redisfailover operator=redisfailover src="generic.go:98"
time="2018-03-13T14:57:59Z" level=info msg="service created" namespace=default service=k8s.service serviceName=rfr-redisfailover src="service.go:51"
time="2018-03-13T14:58:00Z" level=info msg="service created" namespace=default service=k8s.service serviceName=rfs-redisfailover src="service.go:51"
time="2018-03-13T14:58:00Z" level=info msg="configMap created" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:50"
time="2018-03-13T14:58:00Z" level=info msg="configMap created" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:50"
time="2018-03-13T14:58:00Z" level=info msg="podDisruptionBudget created" namespace=default podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:49"
time="2018-03-13T14:58:00Z" level=warning msg="error processing default/redisfailover job (requeued): the server could not find the requested resource" controller=redisfailover operator=redisfailover src="generic.go:155"
time="2018-03-13T14:58:00Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-03-13T14:58:00Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-03-13T14:58:00Z" level=info msg="podDisruptionBudget updated" namespace=default podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:58"
time="2018-03-13T14:58:00Z" level=warning msg="error processing default/redisfailover job (requeued): the server could not find the requested resource" controller=redisfailover operator=redisfailover src="generic.go:155"```

**Comment by jchanam** [comment]
Hi @tanner-bruce,

I've tryed on minikube (to have a fresh clean cluster), and done exactly the same you did.

I's launching the redis failover with not a problem.

```
NAME                                 READY     STATUS    RESTARTS   AGE
redisoperator-6b79fcccb7-ws7jc       1/1       Running   0          2m
rfr-redisfailover-0                  2/2       Running   0          1m
rfr-redisfailover-1                  2/2       Running   0          1m
rfr-redisfailover-2                  2/2       Running   0          46s
rfs-redisfailover-7d9f479b65-lkvnw   1/1       Running   0          1m
rfs-redisfailover-7d9f479b65-nwbtq   1/1       Running   0          1m
rfs-redisfailover-7d9f479b65-xlwmk   1/1       Running   0          1m
```

The only issue I find similar, is this:
```
time="2018-03-15T10:57:41Z" level=error msg="Error processing default/redisfailover: dial tcp :6379: getsockopt: connection refused" controller=redisfailover operator=redisfailover src="generic.go:158"
```

This is caused because the operator connects to the redis and sentinels to check their status, and It's not possible to do it if they are creating, but it's temporal and it's not shown after the first appearance.

The RF is launched after that erros? Are the same you are facing?

Thanks for opening the issue and sorry for the delay

**Comment by pjgg** [comment]
I didn't enable metric exporter, and I have the same issue. 

time="2018-04-02T13:51:36Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:51:37Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:51:37Z" level=info msg="podDisruptionBudget updated" namespace=default podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:58"
time="2018-04-02T13:51:37Z" level=error msg="Error processing default/redisfailover: the server could not find the requested resource" controller=redisfailover operator=redisfailover src="generic.go:158"
time="2018-04-02T13:52:04Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:04Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:04Z" level=info msg="podDisruptionBudget updated" namespace=default podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:58"
time="2018-04-02T13:52:04Z" level=warning msg="error processing default/redisfailover job (requeued): the server could not find the requested resource" controller=redisfailover operator=redisfailover src="generic.go:155"
time="2018-04-02T13:52:04Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:04Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:04Z" level=info msg="podDisruptionBudget updated" namespace=default podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:58"
time="2018-04-02T13:52:04Z" level=warning msg="error processing default/redisfailover job (requeued): the server could not find the requested resource" controller=redisfailover operator=redisfailover src="generic.go:155"
time="2018-04-02T13:52:05Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:06Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:06Z" level=info msg="podDisruptionBudget updated" namespace=default podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:58"
time="2018-04-02T13:52:06Z" level=warning msg="error processing default/redisfailover job (requeued): the server could not find the requested resource" controller=redisfailover operator=redisfailover src="generic.go:155"
time="2018-04-02T13:52:06Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:07Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:07Z" level=info msg="podDisruptionBudget updated" namespace=default podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:58"
time="2018-04-02T13:52:07Z" level=error msg="Error processing default/redisfailover: the server could not find the requested resource" controller=redisfailover operator=redisfailover src="generic.go:158"
time="2018-04-02T13:52:34Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:34Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:34Z" level=info msg="podDisruptionBudget updated" namespace=default podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:58"
time="2018-04-02T13:52:34Z" level=warning msg="error processing default/redisfailover job (requeued): the server could not find the requested resource" controller=redisfailover operator=redisfailover src="generic.go:155"
time="2018-04-02T13:52:34Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:34Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:34Z" level=info msg="podDisruptionBudget updated" namespace=default podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:58"
time="2018-04-02T13:52:34Z" level=warning msg="error processing default/redisfailover job (requeued): the server could not find the requested resource" controller=redisfailover operator=redisfailover src="generic.go:155"
time="2018-04-02T13:52:35Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:36Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:36Z" level=info msg="podDisruptionBudget updated" namespace=default podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:58"
time="2018-04-02T13:52:36Z" level=warning msg="error processing default/redisfailover job (requeued): the server could not find the requested resource" controller=redisfailover operator=redisfailover src="generic.go:155"
time="2018-04-02T13:52:36Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:37Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:58"
time="2018-04-02T13:52:37Z" level=info msg="podDisruptionBudget updated" namespace=default podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:58"
time="2018-04-02T13:52:37Z" level=error msg="Error processing default/redisfailover: the server could not find the requested resource" controller=redisfailover operator=redisfailover src="generic.go:158"

**Comment by jchanam** [comment]
Hi @pjgg,

First of all, sorry for the late answer. I'm checking deeply to find the issue you're facing, but I don't have enough information to get to the problem.

Could you give me the following information?:
* Version of redis-operator
* Version of kubernetes
* Redis failover specification

Also, could you activate the debugging? The flag "-debug" has to be added when running the operator.

Thanks!

**Comment by ese** [comment]
Im closing this since no response. Feel free to reopen if you still have the problem
