### ISSUE TITLE
example dir no updates?

### ISSUE THREAD

**Issue by yxxhero** [spotahome/redis-operator#350]
### Expected behaviour
example dir no updates?
What do you want to achieve?

### Actual behaviour

What is happening? Are all the pieces created? Can you access to the service?

### Steps to reproduce the behaviour

Describe step by step what you've have done to get to this point

### Environment

How are the pieces configured?
* Redis Operator version
* Kubernetes version
* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.

**Comment by ese** [comment]
What example do you miss?

**Comment by yxxhero** [comment]
https://github.com/spotahome/redis-operator/tree/master/example/operator, This directory need update. @ese
