### ISSUE TITLE
Add enviroment variables to redis/sentinel replicas

### ISSUE THREAD

**Issue by zekena2** [spotahome/redis-operator#364]
### Expected behaviour

What do you want to achieve?

 Add environment variables to redis and sentinel pods so I can specify the hostname of these replicas to use the hostnames instead of IP addresses as specified [here](https://redis.io/topics/sentinel#ip-addresses-and-dns-names) 
### Actual behaviour

What is happening? Are all the pieces created? Can you access to the service?
When I put Env field under redis or sentinel section in the RedisFailover it doesn't appear in the deployment and statefulset 

### Steps to reproduce the behaviour

I edited the Redis Failover added some custom configs and env section like here (this exported by `kubectl get RedisFailover <name> -o yaml` 

```yaml
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  generation: 11
  labels:
    app: <app name>
    service: <service name>
  name: <name>
  namespace: default
  resourceVersion: "485235820"
  uid: 8a97e3f3-eeda-40d0-ae15-653b367555a2
spec:
  redis:
    customConfig:
    - replica-announce-ip $MY_POD_HOSTNAME
    - maxmemory-policy volatile-ttl
    - maxmemory 950mb
    env:
    - name: MY_POD_OWNER
      valueFrom:
        fieldRef:
          fieldPath: metadata.ownerReferences.name
    - name: MY_POD_HOSTNAME
      value: $(REDIS_ALIAS).$(MY_POD_OWNER).default.svc.cluster.local
    exporter:
      enabled: true
      image: oliver006/redis_exporter:v1.5.3
    podAnnotations:
      linkerd.io/inject: disabled
    replicas: 3
    resources:
      limits:
        cpu: 100m
        memory: 1024Mi
      requests:
        cpu: 10m
        memory: 32Mi
    terminationGracePeriodSeconds: 120
  sentinel:
    customConfig:
    - down-after-milliseconds 1000
    - failover-timeout 300
    - announce-ip $MY_POD_HOSTNAME
    - resolve-hostnames yes
    - announce-hostnames yes
    - parallel-sync mymaster 1
    env:
    - name: MY_POD_OWNER
      valueFrom:
        fieldRef:
          fieldPath: metadata.ownerReferences.name
    - name: MY_POD_HOSTNAME
      value: $(REDIS_ALIAS).$(MY_POD_OWNER).default.svc.cluster.local
    podAnnotations:
      linkerd.io/inject: disabled
    replicas: 3
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    terminationGracePeriodSeconds: 120

```
### Environment

How are the pieces configured?
* Redis Operator version 1.1.0
* Kubernetes version 1.21
* Kubernetes configuration used (eg: Is RBAC active?) yes

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.

**Comment by zekena2** [comment]
related to enable resolve-hostnames feature I've this error as well from the operator 

time="2022-01-27T10:27:36Z" level=error msg="error on object processing: ERR Unknown option or number of arguments for SENTINEL SET 'resolve-hostnames'" controller-id=redisfailover object-key=default/<app> operator=redisfailover service=kooper.controller src="controller.go:279"
--
<br class="Apple-interchange-newline">

**Comment by rdxmb** [comment]
@zekena2 10 months later I ran into the issue with not working announce-ip here. **Did you get a solution for your problem?** `announce-ip` is not fully supported here, because the operator [always overwrites the IP of the Master with the PodIP](https://github.com/spotahome/redis-operator/blob/master/operator/redisfailover/service/heal.go#L111)

The solution for me is to run redis with `hostNetwork` and make sentinel available via traefik's ingressRoute-tcp . However, I have to add TLS for redis, which is next ...

**Comment by zekena2** [comment]
I didn't find a solution but I didn't really need to. I didn't understand the operator well enough back then so my use case is different. I guess for IngressRouteTCP you can create Certificate object with cert-manager(if you've it) and then use the parameter issuerRef to reference the IngressRouteTCP.
