### ISSUE TITLE
How to use Prometheus annotation

### ISSUE THREAD

**Issue by Kyrremann** [spotahome/redis-operator#37]
I'm trying to communicate with the redis-exporter in each `rfr-` pod, but as the normal Prometheus annotations are missing, and I only have one `service` to communicate with all three of my pods, I don't get the data I want.

Have you thought about adding the annotation to each redis-exporter container? So that we can scrape each of them, instead of a service point?

The annotation I'm thinking about is:
```
  Annotations:  prometheus.io/path=/metrics
                prometheus.io/port=http
                prometheus.io/scrape=true
```

Also, do we really need the service point for Prometheus scraping? Isn't it better to scrape each pod with an redis-exporter, so we get more precise data about the load?

I'm writing the code needed for it for us. Can create a PR when I'm done.

**Comment by jchanam** [comment]
Thanks for the PR @Kyrremann 

The release is created and ready to use: https://github.com/spotahome/redis-operator/releases/tag/0.2.2
