### ISSUE TITLE
Lots of sentinel is down logs

### ISSUE THREAD

**Issue by necipakca** [spotahome/redis-operator#375]
I want to use Redis with hibernate second level cache on k8s. Everything looks fine except lots of WARN logs. Actually all pods are running. Headless service is solution or not ?

### Environment

Redis Operator version  -  v1.1.0
Kubernetes version - 1.21.5
Redisson : 3.15.1

### Logs

 WARN  [redisson-netty-2-30[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                         │
│ 21.02.2022 06:40:17.931 WARN  [redisson-netty-2-30[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                         │
│ 21.02.2022 06:40:22.945 WARN  [redisson-netty-2-19[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.0.14.98:26379 is down                                                            │
│ 21.02.2022 06:40:23.949 WARN  [redisson-netty-2-30[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                         │
│ 21.02.2022 06:40:27.958 WARN  [redisson-netty-2-30[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                         │
│ 21.02.2022 06:40:32.971 WARN  [redisson-netty-2-25[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                         │
│ 21.02.2022 06:40:38.041 WARN  [redisson-netty-2-30[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                         │
│ 21.02.2022 06:40:43.053 WARN  [redisson-netty-2-25[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                         │
│ 21.02.2022 06:40:48.066 WARN  [redisson-netty-2-1[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                          │
│ 21.02.2022 06:40:53.083 WARN  [redisson-netty-2-10[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.0.13.69:26379 is down                                                            │
│ 21.02.2022 06:40:56.091 WARN  [redisson-netty-2-30[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                         │
│ 21.02.2022 06:40:58.102 WARN  [redisson-netty-2-25[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.0.13.69:26379 is down                                                            │
│ 21.02.2022 06:40:59.106 WARN  [redisson-netty-2-30[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                         │
│ 21.02.2022 06:41:03.120 WARN  [redisson-netty-2-11[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.0.14.98:26379 is down                                                            │
│ 21.02.2022 06:41:04.123 WARN  [redisson-netty-2-30[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                         │
│ 21.02.2022 06:41:08.138 WARN  [redisson-netty-2-23[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down                                                         │
│ 21.02.2022 06:41:13.151 WARN  [redisson-netty-2-23[] org.redisson.connection.SentinelConnectionManager: sentinel: redis://10.233.16.227:26379 is down

**Comment by yangvipguang** [comment]
@necipakca  you can create a headless service. we fixed the problem
