### ISSUE TITLE
Improve kustomize experience

### ISSUE THREAD

**Issue by sagikazarmark** [spotahome/redis-operator#377]
Hello!

This is my first issue here, so let me start by saying thanks for your work on this operator.

I created a repository for installing the operator using Kustomize: https://github.com/sagikazarmark/kustomize-spotahome-redis-operator

I was wondering if you were interested in hosting it in this repository. I'd be happy to send a PR if you are open to it.

I'd suggest putting it in the manifests directory (currently only the generated CRD is there). If you are worried about backwards compatibility, it could go somewhere else (`deploy/manifests`?).

Let me know what you think.

**Comment by sagikazarmark** [comment]
Friendly ping :)

**Comment by sagikazarmark** [comment]
Friendly ping :)

**Comment by sagikazarmark** [comment]
Friendly ping :)

**Comment by sagikazarmark** [comment]
Bump

**Comment by ese** [comment]
Happy to count with the feature included in the repository. I think we can use `manifests/kustomize` as placeholder

**Comment by sagikazarmark** [comment]
@ese do you want me to send a PR?

**Comment by sagikazarmark** [comment]
PR sent
