### ISSUE TITLE
Fresh Installation via Helm not working

### ISSUE THREAD

**Issue by pehbehbeh** [spotahome/redis-operator#384]
### Expected behaviour

Create a redisfailover.

### Actual behaviour

Error in operator logs:

> time="2022-03-03T14:18:07Z" level=error msg="error on object processing: the server could not find the requested resource" controller-id=redisfailover object-key=mynamespace/myname operator=redisfailover service=kooper.controller src="controller.go:279"

### Steps to reproduce the behaviour

1. Install operator via Helm.
2. Apply `basic.yaml` example.

### Environment

How are the pieces configured?
* Redis Operator version: Helm Chart 3.1.4
* Kubernetes version: v1.20.15
* Kubernetes configuration used: RBAC active

**Comment by RinckFox** [comment]
The problem here is that the chart uses a release candidate. Is discussed here #393. It is solved simply by defining a stable version, for example:
`helm upgrade redis-operator redis-operator/redis-operator --set="image.tag=v1.1.1"`

**Comment by Ramki33** [comment]
HI @RinckFox  , 

i tried as you suggested above  with   --set="image.tag=v1.1.1"     operators are not created . 
let me know what version is correct to use

**Comment by RinckFox** [comment]
@Ramki33 Operator started without errors on version v1.1.1. What exactly doesn't work for you? What does it mean "operators are not created"?

**Comment by Ramki33** [comment]
Hi @RinckFox , 

we are using openshift  , did following 

#helm repo add redis-operator https://spotahome.github.io/redis-operator
#helm repo update

# helm upgrade -i redis-operator redis-operator/redis-operator --set="image.tag=v1.1.1"
Release "redis-operator" does not exist. Installing it now.
Error: create: failed to create: namespaces **"redis-operaor" not found**

# oc new-project redis-operaor
# helm upgrade -i redis-operator redis-operator/redis-operator --set="image.tag=v1.1.1"
Release "redis-operator" does not exist. Installing it now.
NAME: redis-operator
LAST DEPLOYED: Tue Apr 19 07:34:11 2022
NAMESPACE: redis-operaor
STATUS: deployed
REVISION: 1
TEST SUITE: None

# oc get po -n redis-operaor
No resources found in redis-operaor namespace.

# oc get all  -n redis-operaor
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/redis-operator   ClusterIP   172.30.70.178   <none>        9710/TCP   9m12s

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/redis-operator   0/1     0            0           9m12s

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/redis-operator-7cd4c9496   1         0         0       9m12s

**Comment by smitpatelx** [comment]
To be more specific, for somebody trying to install this package with heml.
```bash
helm repo add redis-operator https://spotahome.github.io/redis-operator
helm repo update

# List all versions
helm search repo redis-operator --versions

# Pick the chart version you want to install and replace it with 3.2.9 below:
helm install redis-operator redis-operator/redis-operator --version="3.2.9"
```
