### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by JorTurFer** [spotahome/redis-operator#391]
Hi!
We are integrating this operator in our infrastructure (thanks for it, it does an awesome job) and we are facing with the problems that [this PR](https://github.com/spotahome/redis-operator/pull/372) solves.

For the moment, we are using the workaround of creating a custom shutdown script with the proper values, but if you could do a release, at least of the code, will be fantastic.

I have checked the repo and I can't see anything about your release plan, so IDK if it's possible to trigger a release, or when it will happen.

Thanks for this operator because really makes our life easier ❤️ ❤️ ❤️

**Comment by JorTurFer** [comment]
Hey!!!
Any news about this?

**Comment by jhhilary** [comment]
Our team would also like the latest chart released to your helm repo if possible. Thank you for the operator!

**Comment by JorTurFer** [comment]
Any update?

**Comment by ese** [comment]
Next release probably this week or next if we find bugs.

**Comment by ese** [comment]
I just published a pre-release https://github.com/spotahome/redis-operator/releases/tag/v1.2.0-rc0
Feel free to test it and report if you find something, thanks!
```
docker pull quay.io/spotahome/redis-operator:v1.2.0-rc0
```

**Comment by ese** [comment]
https://github.com/spotahome/redis-operator/releases/tag/v1.2.0
