### ISSUE TITLE
1.1.1 version is not added to helm repository

### ISSUE THREAD

**Issue by ewypych** [spotahome/redis-operator#393]
### Expected behavior

**What do you want to achieve?**

Have a possibility to install app version 1.1.1 directly from helm repository

### Actual behavior

**What is happening? Are all the pieces created? Can you access to the service?**

Currently only version `1.1.0-rc*` are visible in the helm repository:

```bash
$ helm search repo redis-operator --versions
NAME                         	CHART VERSION	APP VERSION	DESCRIPTION
redis-operator/redis-operator	3.1.4        	1.1.0-rc.1 	A Helm chart for the Spotahome Redis Operator
redis-operator/redis-operator	3.1.3        	1.1.0-rc.1 	A Helm chart for the Spotahome Redis Operator
redis-operator/redis-operator	3.1.2        	1.1.0-rc.2 	A Helm chart for the Spotahome Redis Operator
```

### Steps to reproduce the behavior

**Describe step by step what you have done to get to this point**

1. Add repository according to instruction.
2. Update repository cache.
3. Try to check versions.

### Notes

By solving this issue, you will probably solve #387 as well, because in version 1.1.1 image tag is updated, but no one is able to install redis-operator by helm repository with version 1.1.1 (which has been released a month ago).

**Comment by m-yosefpor** [comment]
this would be nice

**Comment by smitpatelx** [comment]
To be more specific, for somebody trying to install this package with heml.
```bash
helm repo add redis-operator https://spotahome.github.io/redis-operator
helm repo update

# List all versions
helm search repo redis-operator --versions

# Pick the chart version you want to install and replace it with 3.2.9 below:
helm install redis-operator redis-operator/redis-operator --version="3.2.9"
```
