### ISSUE TITLE
Problem with RBAC on openshift 4.8

### ISSUE THREAD

**Issue by maleka12** [spotahome/redis-operator#397]
Hi,
we have installed redis-operator on Openshift v4.8.35 and still facing problems with error:
FailedCreate        statefulset/rfr-redisfailover             create Pod rfr-redisfailover-0 in StatefulSet rfr-redisfailover failed error: failed to create PVC pvcc-rfr-redisfailover-0: persistentvolumeclaims "pvcc-rfr-redisfailover-0" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>

I saw PR #329 but our clusterrole have this rules and it is still not working.

Our clusterrole looks like:
```apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisoperator
rules:
- apiGroups:
  - databases.spotahome.com
  resources:
  - redisfailovers
  - redisfailovers/finalizers
  - persistentvolumeclaims
  - persistentvolumeclaims/finalizers
  - statefulsets/finalizers
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - events
  - configmaps
  - secrets
  - persistentvolumeclaims
  - persistentvolumeclaims/finalizers
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
  ```

Is there anyone who have installed redis-operator on openshift 4.8 and it works correctly with storage? 
Maybe this occurs only on our openshift cluster.

**Comment by Feelas** [comment]
It still seems to be broken.

**Comment by romankovtun** [comment]
> It still seems to be broken.

yeap, it is still broken.

workaround worked for me: set in RedisFailover storage section
`keepAfterDeletion: true`

**Comment by drivebyer** [comment]
Same issue, is there lost permission on the clusterrole.yaml when deploy on OCP?
