### ISSUE TITLE
Redis update process

### ISSUE THREAD

**Issue by mariusstaicu** [spotahome/redis-operator#401]
### Expected behaviour

One of the main reasons for using an operator is that it knows exactly how to perform various maintenance tasks in such a way that there is no downtime and using best recommended actions for the software it "operates". 
Therefore, I would expect redis-operator to perform routine upgrades of the RedisFailover resource with zero downtime.

### Actual behaviour

Whenever changing something to a RedisFailover resource the operator triggers an update of the redis and/or redis-sentinel workloads. The redis upgrade process does not wait for new master re-election, all the pods go down too fast and when they come back up they try to connect to a master that doesn't exist enymore.
This causes 2-3 minutes of downtime of the redis cluster.

### Steps to reproduce the behaviour

1. Have a redis-operator deploy a redisfailover cluster with 3 sentinel nodes, 3 redis nodes.
2. Modify the redisfailover yaml in such a way that a change of redis is needed (change redis version, increase/decrease memory or cpu etc.)

### Environment

How are the pieces configured?
* Redis Operator version: 1.1.1
* Kubernetes version: v1.21.10
* Kubernetes configuration used: GKE cluster with RBAC enabled

Also tried with this example which should help switch master before shutdown, however it doesn't work: https://github.com/spotahome/redis-operator/blob/master/example/redisfailover/custom-shutdown.yaml

Related closed issue here: https://github.com/spotahome/redis-operator/issues/89

**Comment by gwpries** [comment]
I posted some info on https://github.com/spotahome/redis-operator/issues/403, but I've finished my investigation on zero-down-time redisfailover deployments and have a little more to share here.

I encountered a few main problems with pod termination:

1. Additional sidecar pods with different shutdown delays (linkerd-proxy in my case) caused redisfailover to misbehave. I removed these sidecars.
2. I had multiple redisfailover operator pods running, and they were conflicting with each other even though they were in different namespace. I've switched to a global operator pod controlling all of the clusters.
3. The default shutdown script variables incorrect in my case. Try shelling into the pod (`kubectl exec -it <pod> /bin/sh`) and running `env`, then compare that to the contents of `cat /redis-shutdown/shutdown.sh`. In my case, the variables in shutdown.sh were RFS_REDIS_SENTINEL_FOO and they should have been RFS_REDIS_CLUSTER_SENTINEL_FOO
4. I added an additional 30s sleep right before the logic `SENTINEL failover x` to give the new pods time to settle. I'm not sure if this is really needed, but I appreciated a little safety
5. I increased the `terminationGracePeriod` just in case the default 60s wasn't enough time to gracefully terminate. I picked a long window, but they usually shut down within 2 minutes.

After these changes, I'm able to do zero down time deployments of the redisfailover clusters.

**Comment by mariusstaicu** [comment]
I can confirm that I'm not using multiple operators.
However I also saw that the variables in the shutdown script are wrong, not matching the available env variables:
- in script: RFS_REDIS_SERVICE_* 
- available env variables: RFS_<name>_*

So it seems pods don't trigger failover when they shutdown, which should explain the delay with which sentinel realizes a node is down.

**Comment by mariusstaicu** [comment]
seems this is fixed on master by https://github.com/spotahome/redis-operator/pull/372, however it is not released yet, I guess we're all waiting for the next release
