### ISSUE TITLE
Operator updating the resources frequently

### ISSUE THREAD

**Issue by sreejithsoman-mc** [spotahome/redis-operator#410]
Hi,
I have deployed redis operator and a redisfailover . I could see that the operator is continuously updating the resources. please find the logs from operator

> time="2022-05-18T10:14:39Z" level=info msg="configMap updated" configMap=rfr-s-product-data namespace=dev-product-data service=k8s.configMap src="configmap.go:78"
> time="2022-05-18T10:14:39Z" level=info msg="configMap updated" configMap=rfr-readiness-product-data namespace=dev-product-data service=k8s.configMap src="configmap.go:78"
> time="2022-05-18T10:14:39Z" level=info msg="configMap updated" configMap=rfr-product-data namespace=dev-product-data service=k8s.configMap src="configmap.go:78"
> W0518 10:14:39.225467       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
> W0518 10:14:39.232141       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
> time="2022-05-18T10:14:39Z" level=info msg="podDisruptionBudget updated" namespace=dev-product-data podDisruptionBudget=rfr-product-data service=k8s.podDisruptionBudget src="poddisruptionbudget.go:79" 
> time="2022-05-18T10:14:39Z" level=info msg="statefulSet updated" namespace=dev-product-data service=k8s.statefulSet src="statefulset.go:102" statefulSet=rfr-product-data
> W0518 10:14:39.255951       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
> W0518 10:14:39.263082       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
> time="2022-05-18T10:14:39Z" level=info msg="podDisruptionBudget updated" namespace=dev-product-data podDisruptionBudget=rfs-product-data service=k8s.podDisruptionBudget src="poddisruptionbudget.go:79" 
> time="2022-05-18T10:14:39Z" level=info msg="deployment updated" deployment=rfs-product-data namespace=dev-product-data service=k8s.deployment src="deployment.go:102"

operator is deployed on **redis** namespace and Failover is on **dev-product-data** namespace.

We could see the below log on sentinal pods as well

> 1:X 18 May 2022 12:24:39.949 # +set master mymaster 10.244.1.175 6379 down-after-milliseconds 5000
> 1:X 18 May 2022 12:24:39.996 # +set master mymaster 10.244.1.175 6379 failover-timeout 10000
> 1:X 18 May 2022 12:25:10.032 # +set master mymaster 10.244.1.175 6379 down-after-milliseconds 5000
> 1:X 18 May 2022 12:25:10.091 # +set master mymaster 10.244.1.175 6379 failover-timeout 10000
> 1:X 18 May 2022 12:25:40.018 # +set master mymaster 10.244.1.175 6379 down-after-milliseconds 5000
> 1:X 18 May 2022 12:25:40.229 # +set master mymaster 10.244.1.175 6379 failover-timeout 10000
> 1:X 18 May 2022 12:26:10.061 # +set master mymaster 10.244.1.175 6379 down-after-milliseconds 5000
> 1:X 18 May 2022 12:26:10.152 # +set master mymaster 10.244.1.175 6379 failover-timeout 10000
> 1:X 18 May 2022 12:26:39.945 # +set master mymaster 10.244.1.175 6379 down-after-milliseconds 5000
> 1:X 18 May 2022 12:26:39.990 # +set master mymaster 10.244.1.175 6379 failover-timeout 10000
> 1:X 18 May 2022 12:27:09.976 # +set master mymaster 10.244.1.175 6379 down-after-milliseconds 5000
> 1:X 18 May 2022 12:27:10.024 # +set master mymaster 10.244.1.175 6379 failover-timeout 10000
> 1:X 18 May 2022 12:27:39.963 # +set master mymaster 10.244.1.175 6379 down-after-milliseconds 5000
> 1:X 18 May 2022 12:27:40.234 # +set master mymaster 10.244.1.175 6379 failover-timeout 10000

Kubernetes version: v1.21.7
Deployed on : Azure AKS
Operator version: v1.1.1

Please let us know how to fix this?

**Comment by sreejithsoman-mc** [comment]
@ese Could you please help with this? Is this a normal behavior or any kind of issue which needs to be fixed?

**Comment by robcxyz** [comment]
I am also experiencing this. Operator is using ~600m cpu. Having significant impact on performance and seeing lots of disconnects from clients.

**Comment by gwpries** [comment]
We are also seeing leaking CPU cycles after upgrading to 1.1.0 or 1.1.1 (we needed to upgrade for kube 1.22 APIs)

![image](https://user-images.githubusercontent.com/55450466/170580173-e719cd7b-561d-40f0-af5d-49b35ae6c08f.png)

**Comment by sreejithsoman-mc** [comment]
@chobostar Thanks for the info. Any idea why in sentinal we have continuous `+set master mymaster` messages ? Is there any way we can avoid these logs if this is just INFO?I am not seeing any options to reduce the LOG LEVEL.

**Comment by robcxyz** [comment]
Was this issue addressed? I stopped using the operator because of this issue but I'd like to use it again in the future.

**Comment by Wouter0100** [comment]
It seems to me this is how the operator is designed: update all objects every 30 seconds. 

The CPU leak is however not as designed, I'd say. Seems also reported in #386. Could this perhaps possibly be a result of #484 fixed in #485?

**Comment by Wouter0100** [comment]
The CPU leak issue mentioned here as well will be fixed with #485.

**Comment by dkdr** [comment]
> It seems to me this is how the operator is designed: update all objects every 30 seconds.
> 
> The CPU leak is however not as designed, I'd say. Seems also reported in #386. Could this perhaps possibly be a result of #484 fixed in #485?

@Wouter0100 I'm using kyverno which validates every object on change. So when operator is updating objects even that the have not changed it creates additional load on kyverno. It would be great if objects would be updated only when needed. I believe, that this issue exists for more users, however most of them are unaware of that, since everything happens under the hood. We've stumbled on it by accident. 

As changing this behaviour could be troublesome, maybe it would be possible to have configure this https://github.com/spotahome/redis-operator/blob/v1.2.1/operator/redisfailover/factory.go#L24 on deployment level?

**Comment by avthart** [comment]
@dkdr We are facing the same issue with Kyverno and having many redis clusters in our k8s cluster.

Indeed, it would be great if objects would be updated only when needed.
