### ISSUE TITLE
kubelet  Readiness probe failed:

### ISSUE THREAD

**Issue by 522623905** [spotahome/redis-operator#412]
redisoperator-75bf8765c-kkrtr         1/1     Running   0              91s
rfr-redisfailover-0                   0/1     Running   0              89s
rfr-redisfailover-1                   0/1     Running   0              89s
rfr-redisfailover-2                   0/1     Running   0              89s
rfs-redisfailover-6b8648d584-69lzs    1/1     Running   0              89s
rfs-redisfailover-6b8648d584-6skxq    1/1     Running   0              89s
rfs-redisfailover-6b8648d584-fdv8j    1/1     Running   0              89s

Name:         rfr-redisfailover-0
Namespace:    default
Priority:     0
Node:         k8s-worker2/10.131.139.77
Start Time:   Thu, 09 Jun 2022 20:56:41 +0800
Labels:       app.kubernetes.io/component=redis
              app.kubernetes.io/managed-by=redis-operator
              app.kubernetes.io/name=redisfailover
              app.kubernetes.io/part-of=redis-failover
              controller-revision-hash=rfr-redisfailover-8454845c96
              redisfailovers.databases.spotahome.com/name=redisfailover
              statefulset.kubernetes.io/pod-name=rfr-redisfailover-0
Annotations:  <none>
Status:       Running
IP:           10.244.2.8
IPs:
  IP:           10.244.2.8
Controlled By:  StatefulSet/rfr-redisfailover
Containers:
  redis:
    Container ID:  docker://e1d968ecdfc5ea81d57d815f3df0171d44cbbf2f6d1b75deb71d8b74ea55d763
    Image:         redis:6.2.6-alpine
    Image ID:      docker-pullable://redis@sha256:132337b9d7744ffee4fae83f51de53c3530935ad3ba528b7110f2d805f55cbf5
    Port:          6379/TCP
    Host Port:     0/TCP
    Command:
      redis-server
      /redis/redis.conf
    State:          Running
      Started:      Thu, 09 Jun 2022 20:56:42 +0800
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     400m
      memory:  500Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Liveness:     exec [sh -c redis-cli -h $(hostname) ping] delay=30s timeout=5s period=15s #success=1 #failure=6
    Readiness:    exec [/bin/sh /redis-readiness/ready.sh] delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /data from redis-data (rw)
      /redis from redis-config (rw)
      /redis-readiness from redis-readiness-config (rw)
      /redis-shutdown from redis-shutdown-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2qflj (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  redis-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rfr-redisfailover
    Optional:  false
  redis-shutdown-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rfr-s-redisfailover
    Optional:  false
  redis-readiness-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rfr-readiness-redisfailover
    Optional:  false
  redis-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-2qflj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  84s               default-scheduler  Successfully assigned default/rfr-redisfailover-0 to k8s-worker2
  Normal   Pulling    84s               kubelet            Pulling image "redis:6.2.6-alpine"
  Normal   Pulled     84s               kubelet            Successfully pulled image "redis:6.2.6-alpine" in 296.478821ms
  Normal   Created    84s               kubelet            Created container redis
  Normal   Started    84s               kubelet            Started container redis
  Warning  Unhealthy  2s (x6 over 45s)  kubelet            Readiness probe failed:

**Comment by 522623905** [comment]
exit in sentinel pod：

kubectl exec -it rfs-redisfailover-6b8648d584-2bddm -- sh
redis-cli -p 26379

....
master0:name=mymaster,status=sdown,address=127.0.0.1:6379,slaves=0,sentinels=1
...

/data $ redis-cli -p 6379
Could not connect to Redis at 127.0.0.1:6379: Connection refused

sentinel pod can not visit redis？

**Comment by szelenka** [comment]
Do you have AUTH configured? I ran into a similar issue in #417

**Comment by seekelvis** [comment]
@522623905 Have you solve the problem? I have the same issue, even if I configure the auth. @szelenka

**Comment by seekelvis** [comment]
cat basic.yaml 
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
  auth:
    secretPath: redis-auth

**Comment by seekelvis** [comment]
```yaml
cat basic.yaml 
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
  auth:
    secretPath: redis-auth
```

**Comment by szelenka** [comment]
@seekelvis we had to patch the operator to change the probes. It was something along the lines of this:
```bash
"redis-cli -h \"${HOSTNAME:-127.0.0.1}\" -a \"${REDIS_PASSWORD}\" -p 26379 ping",
```
So if the REDIS_PASSWORD is present, it would use that, otherwise it would not.

**Comment by euh2** [comment]
> @seekelvis we had to patch the operator to change the probes. It was something along the lines of this:
> 
> ```shell
> "redis-cli -h \"${HOSTNAME:-127.0.0.1}\" -a \"${REDIS_PASSWORD}\" -p 26379 ping",
> ```
> 
> So if the REDIS_PASSWORD is present, it would use that, otherwise it would not.

It would be nice to have that patched. Being able to use AUTH is essential.
