### ISSUE TITLE
operator complains "error on object processing: the server could not find the requested resource" on kubernetes 1.25

### ISSUE THREAD

**Issue by jelmer** [spotahome/redis-operator#456]
### Expected behaviour

After creating a RedisFailover, I expect pods to be started for redis and the sentinel.

### Actual behaviour

No pods are started. Instead, the operator complains in its logs:

time="2022-08-31T23:30:39Z" level=error msg="error on object processing: the server could not find the requested resource" controller-id=redisfailover object-key=default/redisfailover operator=redisfailover service=kooper.controller src="controller.go:279"

### Steps to reproduce the behaviour

I followed the steps in the guide:

kubectl apply -f https://raw.githubusercontent.com/spotahome/redis-operator/master/manifests/databases.spotahome.com_redisfailovers.yaml
kubectl apply -f https://raw.githubusercontent.com/spotahome/redis-operator/master/example/operator/all-redis-operator-resources.yaml
kubectl create -f https://raw.githubusercontent.com/spotahome/redis-operator/master/example/redisfailover/basic.yaml

I followed the exact same steps in another cluster that's running an older version of Kubernetes, and that worked fine.

### Environment

How are the pieces configured?
* Redis Operator version: current Git Head, version 1.1.0 of the image
* Kubernetes version: 1.25

### Logs

time="2022-08-31T23:32:30Z" level=debug msg="debug mode activated" src="main.go:130"
time="2022-08-31T23:32:30Z" level=info msg="Listening on :9710 for metrics exposure" src="asm_amd64.s:1581"
time="2022-08-31T23:32:30Z" level=info msg="starting controller" controller-id=redisfailover operator=redisfailover service=kooper.controller src="controller.go:233"
time="2022-08-31T23:32:31Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=default service=k8s.configMap src="configmap.go:78"
time="2022-08-31T23:32:31Z" level=info msg="configMap updated" configMap=rfr-s-redisfailover namespace=default service=k8s.configMap src="configmap.go:78"
time="2022-08-31T23:32:31Z" level=info msg="configMap updated" configMap=rfr-readiness-redisfailover namespace=default service=k8s.configMap src="configmap.go:78"
time="2022-08-31T23:32:31Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=default service=k8s.configMap src="configmap.go:78"
time="2022-08-31T23:32:31Z" level=error msg="error on object processing: the server could not find the requested resource" controller-id=redisfailover object-key=default/redisfailover operator=redisfailover service=kooper.controller src="controller.go:279"

**Comment by jelmer** [comment]
Actually, this might be the reverse of #358

**Comment by jelmer** [comment]
Actually, it seems like upgrading to :latest addresses this. Presumably because you switched from policyv1beta to policyv1

**Comment by samof76** [comment]
@jelmer yes this would have been fixed in the lastet one. Ref: https://github.com/spotahome/redis-operator/pull/359

**Comment by jelmer** [comment]
Thanks for confirming! Looking forward to the release, I'll stick to the snapshot until then.
