### ISSUE TITLE
Update deprecated v1beta1.PodDisruptionBudget to v1.PodDisruptionBudget

### ISSUE THREAD

**Issue by szelenka** [spotahome/redis-operator#467]
### Expected behaviour

Add PodDisruptionBudget in k8s past version 1.25

### Actual behaviour

Operator code explicitly references v1beta1.PodDisruptionBudget which is deprecated. This should be updated to v1.PodDistributionBudget
https://pkg.go.dev/k8s.io/api@v0.25.0/policy/v1#PodDisruptionBudget

### Steps to reproduce the behaviour

Install operator on k8s 1.21+ and create a Redis cluster through the Operator, view the Operator logs

### Environment

How are the pieces configured?
* Redis Operator version - v1.1.1
* Kubernetes version - 1.21
* Kubernetes configuration used (eg: Is RBAC active?) - yes

### Logs
```json
{
  "jsonPayload": {
    "message": "policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget",
    "pid": "8"
  },
  "sourceLocation": {
    "file": "warnings.go",
    "line": "70"
  }
}
```

**Comment by szelenka** [comment]
working on a PR this week

**Comment by samof76** [comment]
@szelenka how about this? https://github.com/spotahome/redis-operator/pull/405

**Comment by szelenka** [comment]
my mistake, what's the expected release date for v1.2.0?
