### ISSUE TITLE
is RedisJSON supported in the operator ?

### ISSUE THREAD

**Issue by raviranjanelastisys** [spotahome/redis-operator#468]
is RedisJSON supported in the operator ?

**Comment by samof76** [comment]
I would suggest you follow these steps
- Build you own redis image, with RedisJSON(`.so`) compiled to a know location
- Use your custom Image by passing to the CRD something like this https://github.com/spotahome/redis-operator/blob/master/example/redisfailover/custom-image.yaml
- Use the https://github.com/spotahome/redis-operator#custom-command feature to load the module at runtime
