### ISSUE TITLE
Alpine redis user's uid is the 999, and container securityContext defaults to 1000

### ISSUE THREAD

**Issue by samof76** [spotahome/redis-operator#470]
Ref:

https://github.com/docker-library/redis/blob/master/6.2/alpine/Dockerfile#L4
https://github.com/spotahome/redis-operator/blob/master/operator/redisfailover/service/generator.go#L738-L746

Should we change to be insync?

**Comment by ese** [comment]
It's an interesting but potentially breaking change since current deploys that are using persistance will have to change manually the permissions in the already created files and since it doesn't bring any benefit I can see I would let as it is

**Comment by samof76** [comment]
Agreed! It would not break anything but just to ensure we are using the right gid and uid
