### ISSUE TITLE
Helm install of operator fails, CustomResourceDefinition too long

### ISSUE THREAD

**Issue by jonathon2nd** [spotahome/redis-operator#496]
### Expected behaviour

Installation of operator

### Actual behaviour

Installation fails

### Steps to reproduce the behaviour

Install with `monitoring.enabled` and `monitoring.serviceMonitor` enabled

### Environment

How are the pieces configured?
* Redis Operator version: redis-operator:3.2.3
* Kubernetes version: v1.24.4+rke2r1	
* Kubernetes configuration used (eg: Is RBAC active?): Too vague 

Installing with Argo, which just uses helm chart and values.

### Logs
```
CustomResourceDefinition.apiextensions.k8s.io "redisfailovers.databases.spotahome.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```
![image](https://user-images.githubusercontent.com/52681917/195434489-bd7b05d1-406d-4d25-a6cc-1339a382d767.png)

**Comment by alexey-demyanov** [comment]
But kubectl create is working.

**Comment by jonathon2nd** [comment]
Is this something that can be fixed?

**Comment by sotberd** [comment]
You can use --server-side apply. https://argo-cd.readthedocs.io/en/latest/user-guide/sync-options/#server-side-apply

**Comment by sotberd** [comment]
ArgoCD version ?

**Comment by jonathon2nd** [comment]
v2.4.12

**Comment by sotberd** [comment]
If ```shell 
syncOptions:
      - ServerSideApply=true
     ```  didn't work  
you can try  ```shell
syncOptions:
      - Replace=true
      ```

**Comment by jonathon2nd** [comment]
![image](https://user-images.githubusercontent.com/52681917/196457517-841c0477-0536-4c3b-aa50-6f42b9caf08f.png)
That worked.

**Comment by sotberd** [comment]
Nice 👍

**Comment by sotberd** [comment]
> Confirm. Same if you are trying to kubectl it.
> 
> ```
> # kubectl apply -f crd.yaml 
> The CustomResourceDefinition "redisfailovers.databases.spotahome.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
> ```

try with `kubectl apply -f --server-side crd.yaml`
