### ISSUE TITLE
Unsupported CONFIG parameter: user

### ISSUE THREAD

**Issue by elluvium** [spotahome/redis-operator#505]
### Expected behaviour
Greetings! I'm trying to create a redis user using customConfig reference in RedisFailover CR with following config:

```
..........
sentinel:
    customConfig:
      - >-
        user oidc on ~sessions:* -@all +@read +@set +@connection +select
        +setex +eval
..........
```

### Actual behaviour
Expecting operator to process default redis `user` config param. But receive a message that operator cannot process `user` config param. Is this expected or I'm doing something wrong here?

### Environment
* Redis Operator v1.1.1
* OKD 4.9

### Logs

`time="2022-10-25T17:46:58Z" level=error msg="error on object processing: ERR Unsupported CONFIG parameter: user" controller-id=redisfailover object-key=test/redis-sentinel operator=redisfailover service=kooper.controller src="controller.go:279"`

**Comment by samof76** [comment]
@elluvium the `customConfig` section only supports, `CONFIG SET` options and not `ACL` commands. The is being debated [here](https://github.com/spotahome/redis-operator/issues/457), and yet to be completed.
