### ISSUE TITLE
Add ability of configuring the redis/sentinel image

### ISSUE THREAD

**Issue by jchanam** [spotahome/redis-operator#51]
As tried on the PR https://github.com/spotahome/redis-operator/pull/47, add the ability of configuring the following:
* Redis exporter image and version
* Redis/Sentinel image and version

**Comment by normander** [comment]
Hi, thanks for interested this function. As you suggest in comment to my PR #47 It should be default value when you don't want to specify redis/sentinel image. I'm waiting for add this feature in project. I could also test your solution on my developer environment.
