### ISSUE TITLE
redis service in port 6379 not deployd

### ISSUE THREAD

**Issue by farhadkh000** [spotahome/redis-operator#517]
### Expected behaviour
i deployed operator and use that for setting up a redis sentinel in my cluster 

# k get all -n redis-operator
NAME                                READY   STATUS    RESTARTS   AGE
pod/redis-operator-677f4bd7-fg4tj   1/1     Running   0          4d19h

NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/redis-operator   ClusterIP   10.106.252.113   <none>        9710/TCP   4d19h

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/redis-operator   1/1     1            1           4d19h

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/redis-operator-677f4bd7   1         1         1       4d19h

in my case i deployed redis sentinel in redis-test

# k get all -n redis-test
NAME                                     READY   STATUS    RESTARTS   AGE
pod/rfr-redisfailover-0                  2/2     Running   0          39m
pod/rfr-redisfailover-1                  2/2     Running   0          39m
pod/rfr-redisfailover-2                  2/2     Running   0          39m
pod/rfs-redisfailover-58c78b47c4-lrqg7   2/2     Running   0          39m
pod/rfs-redisfailover-58c78b47c4-qpwr8   2/2     Running   0          39m
pod/rfs-redisfailover-58c78b47c4-r2w7k   2/2     Running   0          39m

NAME                        TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)     AGE
service/rfr-redisfailover   ClusterIP   None          <none>        9121/TCP    39m
service/rfs-redisfailover   ClusterIP   10.97.1.236   <none>        26379/TCP   39m

NAME                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rfs-redisfailover   3/3     3            3           39m

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/rfs-redisfailover-58c78b47c4   3         3         3       39m

NAME                                 READY   AGE
statefulset.apps/rfr-redisfailover   3/3     39m

What do you want to achieve?
i want use redis but in this test clearly sevice for redis by port 6379 not create  
### Actual behaviour

What is happening? Are all the pieces created? Can you access to the service?

### Steps to reproduce the behaviour

Describe step by step what you've have done to get to this point

### Environment kubernetes cluster

How are the pieces configured?
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
  namespace: technical-bigdata-redissentinel-d
spec:
  sentinel:
    replicas: 3
    exporter:
     enabled: true
     image: leominov/redis_sentinel_exporter:1.3.0
    command:
      - "redis-server"
      - "/redis/sentinel.conf"
      - "--sentinel"
      - "--protected-mode"
      - "no"
    customConfig:
      - "down-after-milliseconds 2000"
      - "failover-timeout 3000"
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    exporter: 
     enabled: true
     image: oliver006/redis_exporter:v1.3.5-alpine
     args:
       - --web.telemetry-path
       - /metrics
     env:
       - name: REDIS_EXPORTER_LOG_FORMAT
         value: txt
    command:
      - "redis-server"
      - "/redis/redis.conf"
      - "--protected-mode"
      - "no"
    customConfig:
      - "maxclients 100"
      - "hz 50"
      - "timeout 60"
      - "tcp-keepalive 60"
      - "client-output-buffer-limit normal 0 0 0"
      - "client-output-buffer-limit slave 1000000000 1000000000 0"
      - "client-output-buffer-limit pubsub 33554432 8388608 60"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    storage:
      persistentVolumeClaim:
        metadata:
          name: redisfailover-persistent-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
* Redis Operator version v1.2.2
* Kubernetes version v1.25.3
* Kubernetes configuration used (eg: Is RBAC active?)

### Logs
time="2022-11-12T08:04:47Z" level=info msg="service updated" namespace=redis-test service=k8s.service serviceName=rfr-redisfailover src="service.go:99"
time="2022-11-12T08:04:47Z" level=info msg="service updated" namespace=redis-test service=k8s.service serviceName=rfs-redisfailover src="service.go:99"
time="2022-11-12T08:04:47Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:84"
time="2022-11-12T08:04:47Z" level=info msg="configMap updated" configMap=rfr-s-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:84"
time="2022-11-12T08:04:47Z" level=info msg="configMap updated" configMap=rfr-readiness-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:84"
time="2022-11-12T08:04:47Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:84"
time="2022-11-12T08:04:47Z" level=info msg="podDisruptionBudget updated" namespace=redis-test podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:85"
time="2022-11-12T08:04:47Z" level=info msg="statefulSet updated" namespace=redis-test service=k8s.statefulSet src="statefulset.go:108" statefulSet=rfr-redisfailover
time="2022-11-12T08:04:47Z" level=info msg="podDisruptionBudget updated" namespace=redis-test podDisruptionBudget=rfs-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:85"
time="2022-11-12T08:04:47Z" level=info msg="deployment updated" deployment=rfs-redisfailover namespace=redis-test service=k8s.deployment src="deployment.go:109"
time="2022-11-12T08:07:04Z" level=error msg="Error while getting service rfr-redisfailover in redis-test namespace : services \"rfr-redisfailover\" not found" src="service.go:84"
time="2022-11-12T08:07:04Z" level=info msg="service created" namespace=redis-test service=k8s.service serviceName=rfr-redisfailover src="service.go:88"
time="2022-11-12T08:07:04Z" level=error msg="Error while getting service rfs-redisfailover in redis-test namespace : services \"rfs-redisfailover\" not found" src="service.go:84"
time="2022-11-12T08:07:04Z" level=info msg="service created" namespace=redis-test service=k8s.service serviceName=rfs-redisfailover src="service.go:88"
time="2022-11-12T08:07:04Z" level=info msg="configMap created" configMap=rfs-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:74"
time="2022-11-12T08:07:04Z" level=info msg="configMap created" configMap=rfr-s-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:74"
time="2022-11-12T08:07:04Z" level=info msg="configMap created" configMap=rfr-readiness-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:74"
time="2022-11-12T08:07:04Z" level=info msg="configMap created" configMap=rfr-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:74"
time="2022-11-12T08:07:04Z" level=info msg="podDisruptionBudget created" namespace=redis-test podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:75"
time="2022-11-12T08:07:04Z" level=info msg="statefulSet created" namespace=redis-test service=k8s.statefulSet src="statefulset.go:98" statefulSet=rfr-redisfailover
time="2022-11-12T08:07:04Z" level=info msg="podDisruptionBudget created" namespace=redis-test podDisruptionBudget=rfs-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:75"
time="2022-11-12T08:07:04Z" level=info msg="deployment created" deployment=rfs-redisfailover namespace=redis-test service=k8s.deployment src="deployment.go:99"
time="2022-11-12T08:07:05Z" level=error msg="Make new master failed, master ip: , error: dial tcp :6379: connect: connection refused" src="checker.go:143"
time="2022-11-12T08:07:05Z" level=error msg="Make new master failed, master ip: , error: dial tcp :6379: connect: connection refused" src="checker.go:143"
time="2022-11-12T08:07:05Z" level=error msg="Make new master failed, master ip: , error: dial tcp :6379: connect: connection refused" src="checker.go:143"
time="2022-11-12T08:07:05Z" level=error msg="error on object processing: number of redis nodes known as master is different than 1" controller-id=redisfailover object-key=redis-test/redisfailover operator=redisfailover service=kooper.controller src="controller.go:279"
time="2022-11-12T08:07:17Z" level=info msg="service updated" namespace=redis-test service=k8s.service serviceName=rfr-redisfailover src="service.go:99"
time="2022-11-12T08:07:17Z" level=info msg="service updated" namespace=redis-test service=k8s.service serviceName=rfs-redisfailover src="service.go:99"
time="2022-11-12T08:07:17Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:84"
time="2022-11-12T08:07:17Z" level=info msg="configMap updated" configMap=rfr-s-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:84"
time="2022-11-12T08:07:17Z" level=info msg="configMap updated" configMap=rfr-readiness-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:84"
time="2022-11-12T08:07:17Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=redis-test service=k8s.configMap src="configmap.go:84"
time="2022-11-12T08:07:17Z" level=info msg="podDisruptionBudget updated" namespace=redis-test podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:85"
time="2022-11-12T08:07:17Z" level=info msg="statefulSet updated" namespace=redis-test service=k8s.statefulSet src="statefulset.go:108" statefulSet=rfr-redisfailover
time="2022-11-12T08:07:17Z" level=info msg="podDisruptionBudget updated" namespace=redis-test podDisruptionBudget=rfs-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:85"

**Comment by stevefan1999-personal** [comment]
This is because this operator is only intended for deploying Redis Sentinel cluster. The underlying Redis databases are not exposed. Your application has to be modified to use Sentinel instead.
