### ISSUE TITLE
Master distribution: pick master at random during first boot.

### ISSUE THREAD

**Issue by samof76** [spotahome/redis-operator#523]
![image](https://user-images.githubusercontent.com/98111/203313805-1fdf07ec-cfe1-4c6d-ad9a-2d7a0cd653df.png)

The master distribution, is fairly skewed, and might be cause of worry when running multiple redis-failover deployments and many masters get crowded to a single node.

**Comment by samof76** [comment]
Here is the query...
```
count(redis_instance_info{k8s_cluster_name="$cluster", redisfailovers_role="master"}) by (node)
```

**Comment by ese** [comment]
IMHO this depends a lot on the specific use case and the architecture where you are integrating your Redis clusters.
From my point of view, different Redis clusters are independent so it is not relevant if they share the same node for their masters while they slaves are well distributed across failure domains.
The schedule constraints should be managed by Kubernetes and the operator should look for mechanisms to leverage like `topologySpreadConstraints`, I think maybe a more reliable labeling of the pods to mark the Redis role of Redis instances could help on this task

**Comment by Wouter0100** [comment]
I agree with @ese.

**Comment by samof76** [comment]
Ok makes sense
