### ISSUE TITLE
how can i get the default image tag from helm chart

### ISSUE THREAD

**Issue by willzhang** [spotahome/redis-operator#537]
### Expected behaviour

how can i get the default image tag from helm chart

### Actual behaviour

i want install redis-operator in offline environment, so how can i get the default image tag from helm chart?

- redis operator tag( already get it)
- redis image tag
- redis sentinal image

```
# helm template redis-operator/redis-operator |grep image:
        image: "quay.io/spotahome/redis-operator:v1.2.2"
```

### Steps to reproduce the behaviour

Describe step by step what you've have done to get to this point

### Environment

How are the pieces configured?
* Redis Operator version
* Kubernetes version
* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.

**Comment by ese** [comment]
The images managed by the operator are not defined in the helm chart. Helm only managed the deploy of the redis-operator but redis clusters  deployments and operations are managed by redis-operator. All the images in this case are defined in the redisfailover CRD.
You can find de defaults one here https://github.com/spotahome/redis-operator/blob/ea4f2326c336f9ca2535e36a838bb282c797b86e/api/redisfailover/v1/defaults.go#L6-L8

In case you one to setup your custom ones you can define it in the CRD:
https://github.com/spotahome/redis-operator/blob/master/example/redisfailover/custom-image.yaml
