### ISSUE TITLE
Did you ever think about use Container for redis & sentinel in RedisFailoverSpec

### ISSUE THREAD

**Issue by sillydong** [spotahome/redis-operator#55]
### Expected behaviour

With Container struct we can define more for redis and sentinel like data store, and we can have more flexiable configuration.

### Actual behaviour

We want set permanent store for the redis instance, but we have to modify the redis-operator code.

Code:
```
// RedisFailoverSpec represents a Redis failover spec
type RedisFailoverSpec struct {
	// Redis defines its failover settings
	Redis corev1.Container `json:"redis,omitempty"`

	// Sentinel defines its failover settings
	Sentinel corev1.Container `json:"sentinel,omitempty"`

	// HardAntiAffinity defines if the PodAntiAffinity on the deployments and
	// statefulsets has to be hard (it's soft by default)
	HardAntiAffinity bool `json:"hardAntiAffinity,omitempty"`

	// NodeAffinity defines the rules for scheduling the Redis and Sentinel
	// nodes
	NodeAffinity *corev1.NodeAffinity `json:"nodeAffinity,omitempty"`
}
```

Or is there any better way to set volume for redis data store?

**Comment by jchanam** [comment]
Hi!

The `container` spec is not used, because the Redis and Sentinel are not containers by themselves. They have specific and custom parameters that are not inside the container spec.

**Comment by sillydong** [comment]
I just requested a pr #58 to enable the redis use manually set data store. So that we don't need to change the `redis` part to `container`.
