### ISSUE TITLE
Updating configuration for redis

### ISSUE THREAD

**Issue by basi02** [spotahome/redis-operator#557]
I am not sure how to be able to update configuration of redis service without removing the pods of the old installation. The update strategy for rfr is onDelete so until we dont remove the old pods, the new updated config pods are not instantiated. Idk how to change the updateStrategy for it to be RollingUpdate?

**Comment by zekena2** [comment]
The operator sends the new configs as commands to redis replicas or sentinels. Check [here](https://github.com/spotahome/redis-operator#custom-configurations)

**Comment by basi02** [comment]
Actually wanted to know how to update the configurations like storage and memory and CPU limit etc for the service running in kubernetes. The pods that are installed using helm chart when service is upgraded the pods do not reinstantiate untill we delete the old pods of rfr service

**Comment by basi02** [comment]
With the config that you are talking about we can only update these settings I believe?
      - "maxclients 100"
      - "hz 50"
      - "timeout 60"
      - "tcp-keepalive 60"
      - "client-output-buffer-limit normal 0 0 0"
      - "client-output-buffer-limit slave 1000000000 1000000000 0"
      - "client-output-buffer-limit pubsub 33554432 8388608 60"

**Comment by villainous-hippogriff** [comment]
On line https://github.com/spotahome/redis-operator/blob/fe8090ac7291ee53ac30e534fa1cc03e5759fd10/operator/redisfailover/service/generator.go#L295

Would that be possible to be configurable? If that can be configured from the inputs it would solve out issue.

**Comment by zekena2** [comment]
@basi02 Gotcha, I didn't know what configuration are you talking about. the ondelete strategy is on purpose because the operator is the one that handles the deletion of the pods in a smart sequence, first it deletes slaves and then moves to the master after slaves get ready. I've just tested in v1.2.4 after editing cpu limits pods get deleted.
