### ISSUE TITLE
Issues with deploying a redisfailover on OpenShift

### ISSUE THREAD

**Issue by yotles** [spotahome/redis-operator#591]
Creating a redisfailover on OpenShift with default Security Context Constraints using this operator doesn't seem to work.  It seems that this is due to the runAsUser, runAsGroup parameter in the securityContext for initContainer in deployment ﻿rfs-redisfailover. 
As it mentioned in README I can pass securityContext and containerSecurityContext  with empty object for sentintel and redis and it work as expected. But initConainer still generated with default securityContext:

>       initContainers:
>       - command:
>         - cp
>         - /redis/sentinel.conf
>         - /redis-writable/sentinel.conf
>         image: redis:6.2.6-alpine
>         imagePullPolicy: Always
>         name: sentinel-config-copy
>         resources:
>           limits:
>             cpu: 10m
>             memory: 32Mi
>           requests:
>             cpu: 10m
>             memory: 32Mi
>         securityContext:
>           allowPrivilegeEscalation: false
>           capabilities:
>             drop:
>             - ALL
>           privileged: false
>           readOnlyRootFilesystem: true
>           runAsGroup: 1000
>           runAsNonRoot: true
>           runAsUser: 1000

And this lead to such errors: 

> message: pods "rfs-redisfailover-c8b4d6546-" is forbidden: unable to validate
>       against any security context constraint

So is it possible to add overwriting securityContext and containerSecurityContext for defaults initContainer too? 

Thanks in advance.

**Comment by cfmanteiga** [comment]
Way better, should work too.
