### ISSUE TITLE
redis stack

### ISSUE THREAD

**Issue by shahabeshaghi67** [spotahome/redis-operator#599]
I used Redis stack for the Sentinel and Redis image, and the cluster could not become ready. It seems like Sentinel could not find the master ip and give them to replicas. Is there any issue with that image, or should any settings be set?

**Comment by shahabeshaghi67** [comment]
I used redis stack for the sentinel and redis image and the cluster could not become ready. seems like senitinel could not find master ip and give them to replicas. is there any issue with that image or any settings should be set?

**Comment by carnerito** [comment]
@shahabeshaghi67 I have the same issue, have you solved it?

**Comment by carnerito** [comment]
Oh, I see. Protected Mode should be disabled if the Redis stack is started without auth. [Here](https://github.com/spotahome/redis-operator/blob/master/example/redisfailover/custom-command.yaml) you can see how it can be disabled.

**Comment by lucasleon2107** [comment]
Hi @carnerito , are you using the redis stack image for both too?

**Comment by carnerito** [comment]
@lucasleon2107 Yes, this is what my manifests look like:

```apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: vms
type: Opaque
stringData:
  password: '<password>'
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-stack
  namespace: vms
spec:
  auth:
    secretPath: redis-auth
  sentinel:
    replicas: 3
    image: 'redis/redis-stack-server:6.2.6-v7'
    command:
      - "redis-server"
      - "/redis/sentinel.conf"
      - "--sentinel"
      - "--protected-mode"
      - "no"
      - "--dir"
      - "/data"
    exporter:
      enabled: true
      image: leominov/redis_sentinel_exporter:1.3.0
  redis:
    resources:
      limits:
        memory: 9Gi
    replicas: 3
    image: 'redis/redis-stack-server:6.2.6-v7'
    command:
      - "redis-server"
      - "/redis/redis.conf"
      - "--protected-mode"
      - "no"
      - "--dir"
      - "/data"
      - "--loadmodule"
      - "/opt/redis-stack/lib/redisearch.so"
      - "--loadmodule"
      - "/opt/redis-stack/lib/rejson.so"
    customConfig:
      - "maxmemory 8gb"
    exporter:
      enabled: true
      image: oliver006/redis_exporter:v1.3.5-alpine
      args:
        - --web.telemetry-path
        - /metrics
      env:
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: txt
```
