### ISSUE TITLE
How to connect outside openshift cluster without hostNetwork

### ISSUE THREAD

**Issue by matzik12** [spotahome/redis-operator#625]
### Expected behaviour

I want to connect from outside the k8s cluster without using hostNetwork. My openshift cluster administrator doesnt want to provide this option to my redis. Is there any other way to do it? I found some bad ways that works for me but i want to find a better solution.

### Environment

How are the pieces configured?
* Redis Operator version - 1.2.4
* Kubernetes version - 1.21 - 1.25 / openshift version 4.8 - 4.12

**Comment by Nold360** [comment]
MetalLB is your friend or use NodePort.

**Comment by matzik12** [comment]
@Nold360 Hi and thanks for commenting,
It is not possible for me because of using sentinel and more than one instance of redis. 
I will need 3 NodePorts and to check every time i connect who is the master redis, Im looking for beyter method and already found one. I made a service with NodePort that connects to the redis instance which has master label and than it also makes the switchover while connected to the redis. One little problem (which is ok for me cause i am using outside connections only in dev) is that the switchover of the service accures only when the labels changes between pods (takes me about 1-2 minutes).
