### ISSUE TITLE
No way to make custom Pod Disruption Policy

### ISSUE THREAD

**Issue by importnil** [spotahome/redis-operator#628]
### Expected behaviour

In a k8s cluster maintenance process, single instanced pods should be allowed to halt. Would be good to either set policy's `MaxUnavailable` to 1 if replicas number set in the `RedisFailover` configuration equals 1, or, to be even more flexible, be allowed to manage the policies in complete.

### Actual behaviour

When num. of sentinels and/or Redis instances equals 1, Pod Disruption Policy that is being created by the operator, makes it impossible to put k8s cluster into maintenance, e.g. restart third-party cloud managed nodes, since the operator ensures, that the Policy has **always** `MinAvailable` property set to `1`.

### Steps to reproduce the behaviour

Use 1 replica for any of these: sentinel, redis.

### Environment

* Redis Operator chart ver.: 3.2.8
* k8s ver.: 1.24.6

### Logs

Example line:
`error when evicting pods/"redis-sentinel-5fb9b7ffc-z4qxn" -n "production" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.`

**Comment by ebuildy** [comment]
You can use ``disablePodDisruptionBudget`` configuration for both redis and sentinel, to disable PDB in case of there is a single replica.

**Comment by paretl** [comment]
@ebuildy I don't know if you already tested it, but `disablePodDisruptionBudget` doesn't work for me. Do you have any feebacks on it?
The related issue that I've created: https://github.com/spotahome/redis-operator/issues/653

**Comment by ebuildy** [comment]
I have just tested, this is OK.

You must use the latest CRD, and operator v1.3.0
