### ISSUE TITLE
Redis-operator wont update statefulset with new port configuration (v1.2.0)

### ISSUE THREAD

**Issue by itayvolo** [spotahome/redis-operator#633]
### Expected behaviour

What do you want to achieve?
Answer:
(Argocd) After syncing redisFailover with a custom port key change, redis stateful-set should roll/restart and change the container port to the new custom port

### Actual behaviour

What is happening? Are all the pieces created? Can you access to the service?
Answer:
After syncing redisFailover with a new custom port, redis stateful-set healthcheck fails and pod is stuck in progressing
"Readiness probe failed: unespected Could not connect to Redis at 127.0.0.1:6379: Connection refused"
6379 - new port
7777 - old port

In the stateful-set yaml, I can see that the new port was not updated since the updateStrategy is set to 'OnDelete'
![image](https://github.com/spotahome/redis-operator/assets/72027444/acb48011-8cc4-4dd0-a022-860ca8179b4e)

This is the container's port configuration in the rfr-redis-0 pod's yaml:
![image](https://github.com/spotahome/redis-operator/assets/72027444/8d5adf9b-4786-43ef-8ca9-17b0f00b2f62)

This is the pod's error message:
![image](https://github.com/spotahome/redis-operator/assets/72027444/98c2439b-f476-4134-b2f5-73fc34775100)

### Steps to reproduce the behaviour

Describe step by step what you've have done to get to this point
Answer:
Synced the redisFailover resource with new custom port + new redis image tag (to support the custom port key)

### Environment

How are the pieces configured?
* Redis Operator version
Answer:
Before syncing the changes: v1.1.1 
After syncing the changes: v1.2.4

* Kubernetes version: 1.23

* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.

**Comment by ebuildy** [comment]
well, changing ``port`` is really a bad idea!

- kubernetes Service will be broken
- Sentinel configuration will be broken
- Your application sentinel cache will be broken
