### ISSUE TITLE
Is it ready for production?

### ISSUE THREAD

**Issue by fzyzcjy** [spotahome/redis-operator#634]
Hi thanks for the operator! I wonder whether it is ready for production?

**Comment by ebuildy** [comment]
well, the 1st release were in 2017 ... so I guess yes

**Comment by hashemi-soroush** [comment]
I've seen a lot of people in the issues section saying they are using it in production heavily.

**Comment by fzyzcjy** [comment]
@hashemi-soroush @ebuildy Thank you for the information! From my experience in other repos, sometimes some people say they use in production, and some people point out small or big problems, so I would like to hear a bit more voices. (e.g. pitfalls to avoid, such as which sub-system is less stable)

**Comment by hashemi-soroush** [comment]
I understand. Here are a few of the comments I mentioned. You might find a little bit more of what you are looking for in these issues.
1. https://github.com/spotahome/redis-operator/issues/550#issuecomment-1383111375
2. https://github.com/spotahome/redis-operator/issues/403#issue-1225104719
3. https://github.com/spotahome/redis-operator/issues/315#issuecomment-920996734
4. https://github.com/spotahome/redis-operator/issues/118#issue-413023048
5. https://github.com/spotahome/redis-operator/issues/122#issue-414606758

**Comment by fzyzcjy** [comment]
@hashemi-soroush Thank you!
