### ISSUE TITLE
persistent volumes?

### ISSUE THREAD

**Issue by delfick** [spotahome/redis-operator#64]
Hello,

I was wondering if it's possible to attach persistent volumes to my redis instances and if so how I'd go about doing that?

As far as I can tell the [recommended deployment](https://github.com/spotahome/redis-operator/blob/master/example/redisfailover.yaml) doesn't do that already

Thanks

**Comment by sillydong** [comment]
You may check this out https://github.com/spotahome/redis-operator/pull/61

**Comment by delfick** [comment]
ah cool :)
