### ISSUE TITLE
Services exposed to the outside world by default with no option to change it?

### ISSUE THREAD

**Issue by rafales** [spotahome/redis-operator#647]
### Expected behavior

I want to deploy a redis service inside my cluster in a safe manner.

### Actual behaviour

Redis services are exposed to the outside world via services with type `LoadBalancer`.

### Steps to reproduce the behaviour

Just follow steps in README to deploy the operator, then deploy redisfailover resource.

### Environment

* Redis operator version: 1.3.0-rc0
* Charts version: 3.2.9

AS far as I can see from the source code, there is no way to change this. Operator will deploy a load balancer, which will be accessible form the internet.

<img width="1139" alt="image" src="https://github.com/spotahome/redis-operator/assets/919812/c3a4c68d-3fd7-41db-9829-1f3e8063bfed">

**Comment by hashemi-soroush** [comment]
It was added in PR #627 . You can find the reasoning for publicly exposing those services in comments after [this](https://github.com/spotahome/redis-operator/pull/627#issuecomment-1682135388). PR #646 changes the service type to ClusterIP until a related configuration is added to the CRD.
