### ISSUE TITLE
Support for Redis 7 and operator versioning

### ISSUE THREAD

**Issue by cjabrantes** [spotahome/redis-operator#652]
Hi All,

As far as i understood the current stable version is 1.2.4 and you guys are working in 1.3.0 being as is 1.3.0-rc1.

Do you have an ETA for 1.3.0 stable to be released? will redis 7 be part of it?

Thanks,
Carlos

**Comment by hashemi-soroush** [comment]
You don't have to wait for a new version of the operator to use Redis 7. You can simply change the image of Redis and Sentinel instances in the Redisfailover CR, even upgrade existing instances. Check #637 .
