### ISSUE TITLE
Redis-operator per namespace

### ISSUE THREAD

**Issue by normander** [spotahome/redis-operator#67]
Hi,

How can I delete redis-operator deployment(all pods) from single namespace?

**Comment by jchanam** [comment]
Hi @normander,

If you want to delete a redis-failover from a namespace, you can delete the custom-resource:
```
kubectl -n <NAMESPACE> delete redisfailover <RF_NAME>
```

If you want to delete only the deployments, you can use the labels (but I don't really understand why to do this):
```
kubectl -n <NAMESPACE> delete deployment -l app=redis-failover
```

**Comment by jchanam** [comment]
Hi @normander,

Have you solved your question? Can we close the issue if no further help needed?

Thanks!

**Comment by jchanam** [comment]
I'm closing this issue. If you have any other question or request, please don't hesitate to open a new issue.

Regards!
