### ISSUE TITLE
how to configure redis to have a persistence of `RDB+AOF` mode.

### ISSUE THREAD

**Issue by zeddit** [spotahome/redis-operator#670]
### Expected behaviour
find the configuration spec to set redis persistence mode.

What do you want to achieve?
customize the persistence mode of redis.

### Actual behaviour
no option for that value.

**Comment by indiebrain** [comment]
Have you read about the `customConfig` config key in the CRD? 

You can add custom `redis.conf`-like config values here. The operator uses `CONFIG SET` to set the values into the redis nodes. 

From the example resource defintions:

https://github.com/spotahome/redis-operator/blob/632aa3da88ee2a28ccb9fc4f571ddcb556dbd713/example/redisfailover/custom-config.yaml#L13-L20

One can configure RDB using Redis' `save` config directive and AOF persistence using Redis' `appendonly` directive.
