### ISSUE TITLE
if we have k8s watch the redis nodes and expose master service directly, then why we still need sentinels?

### ISSUE THREAD

**Issue by zeddit** [spotahome/redis-operator#671]
### Expected behaviour
remove sentinels by some configurations.

What do you want to achieve?

### Actual behaviour
even if I set sentinel to a number of 0, there will still be sentinels.

**Comment by wusendong** [comment]
If you don't use sentinels, then when the master fails and can't be recovered, then no failover is triggered, and the remaining slaves don't become masters.

**Comment by zeddit** [comment]
@wusendong great thanks for your help.
the problem is that when I want to expose redis service to the outside of the k8s cluster, if I use sentinels, the master IP which sentinels report could not be accessed from the outside of the k8s cluster, because it's a intranet IP, e.g. 10.43.0.0/24
