### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by skipworkgh** [spotahome/redis-operator#677]
What is the status of this project? There doesn't seem to happen a lot recently.

**Comment by siegenthalerroger** [comment]
Always ironic when the `stale` flag is set on issues like this.

**Comment by lv2u** [comment]
I guess that answers the question...

**Comment by KlavsKlavsen** [comment]
seems someone needs to fork it - as there's plenty of PRs for the project - but no maintainer

**Comment by KlavsKlavsen** [comment]
@ese are you looking for maintainer help or are you not using this yourself anymore and don't have time for it at all?

**Comment by onedr0p** [comment]
For those looking for an actively developed alternative

https://github.com/OT-CONTAINER-KIT/redis-operator

But who knows what the status of any these projects will become after the recent redis license change.

**Comment by jonathon2nd** [comment]
Bummer that it looks like this project is not being maintained going forward :/ 

Optree can not [bootstrap](https://github.com/OT-CONTAINER-KIT/redis-operator/discussions/865).
Nor can Redis Enterprise operator, by nature of it only supporting redis cluster.

I am not seeing another viable redis operator to compare spotahome's to.

This operator was unique, enjoyed working with it.

**Comment by cnd4** [comment]
The question already go an answer in [august 2022](https://github.com/spotahome/redis-operator/issues/422#issuecomment-1232199585) and even in [septembre 2021](https://github.com/spotahome/redis-operator/issues/315#issuecomment-920996734).

Maybe Spotahome is using he operator and it's working for them so they don't dedicate time/resources to this project? 
(This is not an insult, I can understand that a company don't want to spend resources on a projet that is working fine for their use case)

I find it really difficult to find a good an maintained operator for Redis on Kubernetes. I hope the fork found by @onedr0p will stay active.

Edit: typo.

**Comment by jonathon2nd** [comment]
I have tried in vain to find an operator to switch to. ~~Guess it is back to bitnami/redis~~ [NVM](https://github.com/bitnami/charts/issues/29094)

Adding my doc in case it helps out anyone else.



### Optree Redis Operator
Redis Sentinel

I would not use this is production, does not look prod ready.

https://ot-redis-operator.netlify.app/docs/getting-started/sentinel/
Their doc is out of date it seems?

https://github.com/OT-CONTAINER-KIT/redis-operator

v0.16.0 version for operator came out a [while ago](https://github.com/OT-CONTAINER-KIT/redis-operator/releases/tag/v0.16.0), but no image?

![image](https://github.com/spotahome/redis-operator/assets/52681917/b80bec8d-3a72-4939-ba94-aa97ae7de015)

latest image is v0.15.1

https://quay.io/repository/opstree/redis-operator?tab=tags

 

redis image: https://quay.io/repository/opstree/redis?tab=tags

sentinel image: https://quay.io/repository/opstree/redis-sentinel?tab=tags

 

### KubeDB
Redis Sentinel?

License? https://kubedb.com/articles/deploying-redis-database-using-kubernetes-redis-operator/#pre-requisites 
https://appscode.com/blog/post/relicensing/ 

https://github.com/kubedb?q=&type=all&language=&sort=

https://kubedb.com/docs/v2024.3.16/setup/install/kubedb/

https://kubedb.com/docs/v2024.3.16/guides/redis/

https://kubedb.com/docs/v2024.3.16/guides/redis/sentinel/redis-sentinel/

https://kubedb.com/docs/v2024.3.16/guides/redis/quickstart/quickstart/

Not able to bootstrap from existing master.

### Redis Enterprise Operator

Redis Cluster only! Therefor not able to bootstrap from existing master.

Requires a license: https://wiki.fpinfra.net/books/kubernetes-Ohq/page/redis-enterprise-operator

https://redis.io/docs/latest/operate/kubernetes/deployment/quick-start/
Codeset not open, releases added to doc repo, https://github.com/RedisLabs/redis-enterprise-k8s-docs, with other yamls

**Comment by KlavsKlavsen** [comment]
Fair.. We've chosen to work with opstree in our tree https://github.com/Obmondo/kubeaid/tree/master/argocd-helm-charts/redis-operator - as atleast its in Go - so we have programmers who can assist.. :crossed_fingers:

**Comment by lord-kyron** [comment]
Hi all,
I've decided to try to maintain this project, but since it seems dead now, I've made a fork.
Here is the fork link - https://github.com/lord-kyron/redis-operator
Since I am still learning to build and maintain an operator, I would like to ask all currently active contributors to help add features, approve pull requests, etc., in the new fork.
Another essential thing to mention is that the fork is forked without all currently pending pull requests. Please, all contributors who are still active - try to re-create and submit your pull requests in the fork. I will add you all as contributors there. I will try to make a comparison, and all currently pending pull requests that are not re-created will be forcefully pulled and merged in the fork later.

**Comment by amalic** [comment]
@KlavsKlavsen The Opstree Operator does not work for me. Their documentation is not up to date. After navigating around their documentation I managed to get a cluster running but it doesn't seem to do what it sould do.

Tagging top 4 committers of this repo:

@ese @hoffoo @samof76 @raghu-nandan-bs: Any update on the status of this project?

**Comment by KlavsKlavsen** [comment]
@amalic one of my guys tested it out - and documented how to use it in our KubeAid project : https://github.com/Obmondo/kubeaid/tree/master/argocd-helm-charts/redis-operator - I hope its useful

**Comment by amalic** [comment]
> @amalic one of my guys tested it out - and documented how to use it in our KubeAid project : https://github.com/Obmondo/kubeaid/tree/master/argocd-helm-charts/redis-operator - I hope its useful

Thank you. Saw that link in your previous comment. Not sure what to do with it tbh. In case you want to chat, you can contact me on LinkedIn (see my public Github page for the link).

**Comment by KlavsKlavsen** [comment]
@amalic you just : kubectl apply -f https://github.com/Obmondo/kubeaid/blob/master/argocd-helm-charts/redis-operator/examples/redis-example-with-backup-exclusion.yaml
after having installed the redis operator - and you'll get your redis cluster

**Comment by wangyelei** [comment]
maybe can try https://github.com/apecloud/kubeblocks
