### ISSUE TITLE
helm charts 3.3.0 install err

### ISSUE THREAD

**Issue by liupeng0518** [spotahome/redis-operator#679]
### Expected behaviour

What do you want to achieve?

### Actual behaviour

What is happening? Are all the pieces created? Can you access to the service?

merged this pr :https://github.com/spotahome/redis-operator/pull/631, install has an err:
```
❯ helm upgrade --install redis-operator redis-operator/redis-operator --version 3.3.0                                                                                          ─╯
Error: failed to install CRD crds/databases.spotahome.com_redisfailovers.yaml: error parsing : error converting YAML to JSON: yaml: line 4: did not find expected node content
helm.go:84: [debug] error parsing : error converting YAML to JSON: yaml: line 4: did not find expected node content
```
### Steps to reproduce the behaviour

Describe step by step what you've have done to get to this point

### Environment

How are the pieces configured?
* Redis Operator version
* Kubernetes version
* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.

**Comment by TartanLeGrand** [comment]
It is normal for the crd folder not to be templetised.

**Comment by carnerito** [comment]
@liupeng0518 Did you managed to solve this? I'm having same issue and I'm not sure how to preceed with this.

**Comment by liupeng0518** [comment]
> @liupeng0518 Did you managed to solve this? I'm having same issue and I'm not sure how to preceed with this.

helm fetch redis-operator/redis-operator --version 3.3.0

and delete this commit https://github.com/spotahome/redis-operator/pull/631/files

then helm install

**Comment by carnerito** [comment]
Thanks @liupeng0518 
I ended up installing operator by directly applying manifests with kubectl.

**Comment by TartanLeGrand** [comment]
Or maybe you can use the version before the 3.3.0 😄

**Comment by piyoki** [comment]
I got the same errors.

**Comment by tpmccallum** [comment]
Same, got the following error:

```bash
$ helm repo add redis-operator https://spotahome.github.io/redis-operator
"redis-operator" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "redis-operator" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm install redis-operator redis-operator/redis-operator
Error: INSTALLATION FAILED: failed to install CRD crds/databases.spotahome.com_redisfailovers.yaml: error parsing : error converting YAML to JSON: yaml: line 4: did not find expected node content
```

**Comment by carnerito** [comment]
not stale

**Comment by mhbahmani** [comment]
I have the same issue.
kubectl v1.25
k8s cluster v1.22

**Comment by mhbahmani** [comment]
There is an active MR for this problem at #655, but this project seems too abandoned for this MR to get merged :)

**Comment by romanlytovchenko** [comment]
Maybe this could be helpful for someone
`helm ...  --post-renderer-args='s/{{.*}}/\#/'  --post-renderer="sed"`

**Comment by rotemjac** [comment]
not stale
