### ISSUE TITLE
Issue while applying helm chart

### ISSUE THREAD

**Issue by tornado67** [spotahome/redis-operator#700]
### Expected behaviour

A redis operator has to be installed successfully.

### Actual behaviour
Fails out of the box.
Command
` helm install redis-operator redis-operator/redis-operator` 

fails with the following error:
```
PS C:\Users\user\Documents\projects\p1\cicd> helm install redis-operator redis-operator/redis-operator
Error: INSTALLATION FAILED: failed to install CRD crds/databases.spotahome.com_redisfailovers.yaml: error parsing : error converting YAML to JSON: yaml: line 4: did not find expected node content
```
### Steps to reproduce the behaviour

Execute  ` helm install redis-operator redis-operator/redis-operator`

### Environment
EKS cluster platform version eks.7
K8s version - 1.29

**Comment by cehoffman** [comment]
This was introduced between the 3.2.9 and 3.3.0 chart versions. I just tried updating the chart and got a similar error to above.

**Comment by warmfusion** [comment]
I ran into this problem, but it's a side-effect of Helm's specific design and not a bug persay.

Helm explicitly does not support templating in CRD resources.

https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#:~:text=This%20is%20also%20the%20reason%20behind%20removing%20templating%20support%20from%20CRDs.
