### ISSUE TITLE
Service pointing to master node

### ISSUE THREAD

**Issue by asuvorkin** [spotahome/redis-operator#76]
Is it possible to configure a service directly pointing to the Master node of Redis in failover?
Or may be to have Operator put and update label 'Master' according to the current master node from Sentinel? So if failover happens Operator removes the label from previous Master and moves it the new one.

**Comment by rhefner1** [comment]
What's the use case for that? Using a Redis client without Sentinel support?

**Comment by asuvorkin** [comment]
yes. Let's say I need to upload batch file to Redis using redis-cli which is out my k8s cluster

**Comment by rhefner1** [comment]
Sure, I understand but exposing the Redis master with a public service probably isn't the best thing. IMO a better way to do that is either through VPN (I use [this one](https://github.com/helm/charts/tree/master/stable/openvpn) in my cluster) so redis-cli can connect directly to it or using remote storage as a backend (upload from local machine to S3, download from S3 into temporary pod, upload from temporary pod into redis).

You can kind of fake sentinel support in redis-cli by doing the following:

```
redis_master_ip=$(redis-cli --raw -h rfs-staging-manager-redis-ha.staging.svc.cluster.local -p 26379 sentinel master mymaster | sed -n 4p)
redis-cli -h ${redis_master_ip} -p 6379
```

**Comment by asuvorkin** [comment]
Right, in this case redis_master_ip will be ip of pod running the Master, and I want to access it from our private network, not through Internet.
I'm running k8s cluster on premise, not on Amazon, Azure etc.

**Comment by dustinchilson** [comment]
I also have a need for something like this, our client does not support sentinel and I am hosted on a cloud provider. I'd like use an ingress to route into the master redis node from outside the cluster.

If the Operator where monitoring sentinel and labeling the redis pods as master/slave then a service could just point to the master which negates the need for twemproxy.

Client -> Ingress IP -> redis master service.

Or

Could we consider deploying something like [tuananh/kubernetes-twemproxy](https://github.com/tuananh/kubernetes-twemproxy) as part of the operator? This uses sentinel to determine which redis node is master and use that one for connections. 

Client -> Ingress IP -> twemproxy service -> sentinel -> redis master.

**Comment by jchanam** [comment]
I agree with @rhefner1, the idea of using a Redis Failover is accessing always over Sentinel. @asuvorkin  if you want to access from outside the cluster, you should have other piece, external to the Redis, to allow doing so.

@dustinchilson that is out of the scope of the Redis Operator. The way of doing that is having an external piece as you're proposing. You can directly deploy together a redis-failover and that software, there's no need of update on the operator to do so.
