### ISSUE TITLE
Redis-operator per namespace or one for whole cluster?

### ISSUE THREAD

**Issue by normander** [spotahome/redis-operator#78]
I would like to deploy redisoperator and RedisFailover per namespace. How can I do this? For now each redisoperator trying to manage all RedisFailover.

**Comment by str1k3r** [comment]
actually, I have the same request. I'm having 2 separate environments in the same clusters
dev-* and prod-*
so, would be nice to have (if possible) completely separated instances of all redis components.

**Comment by ese** [comment]
@str1k3r @normander currently it is not possible run isolated instances of redis-operator controller in the same cluster.

**Comment by rhefner1** [comment]
Like @str1k3r said, it would be best to roll out new versions of operator to the staging environment (which is just a separate namespace in our cluster) to see if they work as expected and then roll them out to prod. 

It also could limit the impact of this issue: https://github.com/spotahome/redis-operator/issues/89

**Comment by str1k3r** [comment]
> [](https://github.com/spotahome/redis-operator/issues/89)

very useful case. thanks @rhefner1

**Comment by normander** [comment]
@jchanam How can I delete only redis cluster(statefulset and deployment) per namespace? Right now when I'm doing this, redis-operator recreate statefulset and deployment.

**Comment by jchanam** [comment]
If you want to delete a deployed RedisFailover, you just have to delete that custom resource:

```bash
kubectl -n <namespace> delete redisfailover <rf-name>
```

The redis operator is always checking the redis failovers deployed are alive and available. That's why, if you delete the statefulsets or the deployments, they appear again.
