### ISSUE TITLE
storage is not added to deployment on configuration changed

### ISSUE THREAD

**Issue by nephe** [spotahome/redis-operator#79]
### Expected behaviour

Add persistentVolumeClaim storage to deployment.

### Actual behaviour

PersistentVolumeClaim is not added, remains EmptyDir.

### Steps to reproduce the behaviour

Create deployment without storage (EmptyDir). Then add storage and update deployment. Storage won't be added.
If storage is create within initial deployment, PersistentVolumeClaim is added.

### Environment

How are the pieces configured?
* Redis Operator version
master (7bba835)
* Kubernetes version
v1.8.12

**Comment by jchanam** [comment]
Hi @nephe!

As the shows of the Operator shows, that is a limitation on Kubernetes:
`Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.`

So, I'm sorry, but doing that is not possible.
