### ISSUE TITLE
Make exporter probes optional

### ISSUE THREAD

**Issue by rhefner1** [spotahome/redis-operator#84]
For monitoring, we use InfluxDB instead of Prometheus. For all of our other pods, we run telegraf as a sidecar inside of the pod. The existing exporter functionality in redis-operator is perfect for this except for the readiness/liveness probes - telegraf doesn't accept HTTP requests on `/metrics`.

I have an internal fork that just comments out the probes and it works well, but I'm sure other people will have this as well. Can there just be a boolean value in the exporter config that turns the probes on or off?

cc: @jchanam

**Comment by jchanam** [comment]
Hi @rhefner1,

I don't know if it's better to have an option to disable them, or the possibility of setting those probes (that would allow to leave them empty).

Could you prepare a PR with this improvement?

Thanks!!!
