### ISSUE TITLE
Document split brain error message

### ISSUE THREAD

**Issue by rhefner1** [spotahome/redis-operator#85]
In [logic.md](https://github.com/spotahome/redis-operator/blob/master/docs/logic.md), it says "Most of the problems that may occur will be treated and tried to fix by the controller, except the case that there are a [split-brain](https://en.wikipedia.org/wiki/Split-brain_(computing)). **If happens to be a split-brain, an error will be logged waiting for manual fix**."

I tried looking through the source but couldn't find out what error message is actually printed. I'd like to add this to our alerting system so we know if this happens - what does an example error message look like?

**Comment by jchanam** [comment]
Hi!

Here you have the line with the error message:

https://github.com/spotahome/redis-operator/blob/bac9c2f798437890e4b3c153e68d5fc94bf42625/operator/redisfailover/checker.go#L55-L57

As you can see, an error is add to the metrics, so you can use them to raise an alert.

**Comment by rhefner1** [comment]
Great, thanks!
