### ISSUE TITLE
Logging a lot of "Possible SECURITY ATTACK detected"

### ISSUE THREAD

**Issue by Kyrremann** [spotahome/redis-operator#96]
I was wondering if anyone else was experincing a ton of the following message in their logs?

> Possible SECURITY ATTACK detected. It looks like somebody is sending POST or Host: commands to Redis. This is likely due to an attacker attempting to use Cross Protocol Scripting to compromise your Redis instance. Connection aborted.

Don't believe there are any attacks, but can't really understand why we would get them. Could it be that wrong sentinels/containers are trying to connecting? Or that some framework are communicating on the wrong protocol with the Redis?

**Comment by jchanam** [comment]
I've never seen that error messages. I'll keep an eye just in case.

Has any other user seen this? More information will help :)

**Comment by rhefner1** [comment]
@Kyrremann I don't see any of those security attack messages in my setup. I believe it only happens when you try to access Redis over HTTP. Do you have Redis exposed publicly to the internet? Or do you have a misconfiguration in your client?

**Comment by Kyrremann** [comment]
It's not exposed to the internet, but we do communicate with Redis over http. 
I don't know how our users have configured their apps, but it may be misconfiguration.

Is there a problem communicating over http with Redis?

**Comment by rhefner1** [comment]
@Kyrremann I'm not quite sure what you mean. Redis is not a HTTP server [1] and doesn't have any endpoint that you can make HTTP calls do (at least that I'm aware of). The clients communicate with it using the Redis protocol over TCP.

[1] https://github.com/antirez/redis/issues/3807#issuecomment-279820476

**Comment by Kyrremann** [comment]
I was talking about the connection URL you connect to. We use HTTP there, not HTTPS. Aka the address is `http://rfs-nais-testapp`.

**Comment by rhefner1** [comment]
But your connection URL shouldn't be HTTP because Redis doesn't serve over HTTP. It also doesn't serve on port 80 (as the connection string you put above implies). It should look like: `redis://rfs-myproject:6379/1` (change the name and the database number).

**Comment by Kyrremann** [comment]
I forgot to reply. I've been thinking about it, there may be some prometheus scraping or similar that maybe triggers this warning.

**Comment by jfrabetti** [comment]
I am experiencing this error.  I connect to Redis using the R client library rredis (_redis = redisConnect( host=redisHost, port=redisPort, returnRef=TRUE )_ and redisSet(redis_key,charToRaw(X))) and/or the Python client library redis (r_edis = edis.Redis(host=hostRedis, port=6379)_).  The timestamps of this error message every minute.  Is there a way to find out the origin of the "attack"? Could it have anything to do with the proxy?

**Comment by hand-knitr** [comment]
I am seeing this error too, I have Redis launched in Docker container in Kubernetes. I connect to it using both a Python and a R client. Could it have something to do with my company proxy?

**Comment by VerosK** [comment]
@hand-knitr I've ran into same issue. I would like to ask you for details.

Do you use Prometheus exporters?  Can you show annotations of your service?

I'm suspecting wrong annotations on the service.

Redis-operator generated anotation: `prometheus.io/port: "http"` for the `rfr-` service.

After updating the annotation to `prometheus.io/port: "9121"`, the message *Possible SECURITY ATTACK detected* disappeared.  When I used the same annnotation for standalone Redis, it produced same message.

The code which generates the annotations is at [generator.go#L65][here].

[here]: https://github.com/spotahome/redis-operator/blob/master/operator/redisfailover/service/generator.go#L65

**Comment by sprinkaan88** [comment]
I do I go about adding in an exporter ?
Is it supported ... the helm charts seem to suggest so, but adding it on the redis spec with deployment method doesn't work.

**Comment by madma** [comment]
> I am seeing this error too, I have Redis launched in Docker container in Kubernetes. I connect to it using both a Python and a R client - so it is not the same as [this issue](https://github.com/antirez/redis/issues/3807) which probably should be closed. Could it have something to do with my company proxy?

good hunch about company vpn! i have a similar setup -- issue turned out to be my company vpn (invalid cert on connection), which seems to trigger the warning on my redis container in docker. to resolve i did the following:

1. disconnected from my company vpn
2. re-launched affected services / programs (in my case, connection from rails console was being rejected by redis container, generating the `security attack` error -- just had to re-run `rails c`)
3. reconnect to company vpn

✌️

**Comment by americrypt** [comment]
I've narrowed this down a bit, and **can reproduce the error**. I use VS Code's Docker extension to manage my Redis Docker image: `docker run --rm -d  -p 6379:6379/tcp redis:latest`

If I then look at the log files (_VS Code - right click the container - View Logs_) there is NO mention of this error. If I then do (_VS Code - right click the container - Open in Browser_) a browser tab opens and tells me:

> This page isn’t working

And if I then look at the log files **again**, I will see this error has been appended to the log:

> Possible SECURITY ATTACK detected. It looks like somebody is sending POST or Host: commands to Redis. This is likely due to an attacker attempting to use Cross Protocol Scripting to compromise your Redis instance. Connection aborted.

I'm not convinced this is incorrect behavior if that is what anyone is thinking, but I do certainly understand that in some environments with lots of HTTP activity this error log could happen often enough so as to fill hard drives.

**Comment by iamliji** [comment]
> I've narrowed this down a bit, and **can reproduce the error**. I use VS Code's Docker extension to manage my Redis Docker image: `docker run --rm -d -p 6379:6379/tcp redis:latest`
> 
> If I then look at the log files (_VS Code - right click the container - View Logs_) there is NO mention of this error. If I then do (_VS Code - right click the container - Open in Browser_) a browser tab opens and tells me:
> 
> > This page isn’t working
> 
> And if I then look at the log files **again**, I will see this error has been appended to the log:
> 
> > Possible SECURITY ATTACK detected. It looks like somebody is sending POST or Host: commands to Redis. This is likely due to an attacker attempting to use Cross Protocol Scripting to compromise your Redis instance. Connection aborted.
> 
> I'm not convinced this is incorrect behavior if that is what anyone is thinking, but I do certainly understand that in some environments with lots of HTTP activity this error log could happen often enough so as to fill hard drives.

- and response in postman is: 503 service is unavailable.
any solution?
