### ISSUE TITLE
Safety of replication when master has persistence turned off

### ISSUE THREAD

**Issue by rainhacker** [spotahome/redis-operator#97]
Hello, Firstly, thanks for creating and sharing this operator! It makes the operational aspect of Redis very manageable.

I'm trying to find whether this case is handled by the operator:  https://redis.io/topics/replication#safety-of-replication-when-master-has-persistence-turned-off

I'm new to kubernetes but  this is how I think the issue could manifest:
If master fails, kubernetes will try to bring up the master pod again. If persistence is disabled and master pod is up before sentinels can elect a new master - it will be empty. Slaves will resync from master and they'll be empty as well.  

Is this a valid scenario that the operator can run into, if yes- does the operator ensures old master is restarted as slave after sentinel elects new master ?

**Comment by jchanam** [comment]
Hi!

I agree with redis documentation. If you want to prevent losing data, I'd recommend you to enable persistence, so the information is saved periodically on a persistent disk.

The case you're describing is possible, if there are some factors:
1. The redis pod working as master is restarted.
2. The pod is up before a failover.
3. The pod has the same IP (so it's treated as the same node).

I think this case is difficult to be seen, although it's possible. This is not taken into account at this moment, but I think it's a good idea to keep in mind for improving the check&heal algorithm.

Thanks for the issue!

**Comment by ese** [comment]
This issue must be fixed in latest releases
